objects/Account.object
<CustomObject>
    <fields>
        <fullName>Veeva_ID__c</fullName>
        <externalId>true</externalId>
        <label>Veeva ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <formula>if(LEN(Address_Line_1__c)&gt;0, Address_Line_1__c&amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(Address_Line_2__c)&gt;0, Address_Line_2__c&amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c)&gt;0, City__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c)&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Postal_Code__c)&gt;0, Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0, Country__c,&quot;&quot;)</formula>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_VID__c</fullName>
        <label>Entity VID</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>GHAD-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Veeva_ID__c</fullName>
        <externalId>true</externalId>
        <label>Veeva ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AddressTriggerTest.cls
@isTest
public class AddressTriggerTest {
    @isTest
    public static void test1(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Veeva_ID__c = '123456';
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'Test Contact';
        con.Veeva_ID__c = '789456';
        con.AccountId = acc.Id;
        insert con;
        
        Address__c addObj1 = new Address__c();
        addObj1.Entity_VID__c = '789456';
        insert addObj1;
        
        Address__c addObj2 = new Address__c();
        addObj2.Entity_VID__c = '123456';
        insert addObj2;
    }
}