objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AdminTriggerToggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BypassSampleUpdateTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Sample Update Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Admin Trigger Toggle</label>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT(Account__r.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/sampleRecordUpdateBatchTest.cls
@IsTest
public with sharing class sampleRecordUpdateBatchTest {

    @TestSetup
    public static void setupObjects(){
        AdminTriggerToggle__c toggle = new AdminTriggerToggle__c();
        toggle.BypassSampleUpdateTrigger__c = false;
        insert toggle;

        //Create Account
        Account a1 = (Account) TestFactory.createSObject(new Account(Account_Type__c = 'Clinical Account US'), true);
        //Create Contact
        Contact c1 = (Contact) TestFactory.createSObject(new Contact(AccountId = a1.Id),true);
        //Create Samples
        Guardant_360_Sample__c[] samples = (Guardant_360_Sample__c[]) TestFactory.createSObjectList(new Guardant_360_Sample__c(Contact__c = c1.Id, Account__c = a1.Id),10);
        for (Integer i = 0; i < samples.size(); i++) {
            Guardant_360_Sample__c sample = samples.get(i);
            sample.Date_Received__c = Date.today() - i;
        }
        insert samples;
    }


    @IsTest
    public static void sampleBatch() {
      
        test.starttest();
       Database.executeBatch(new sampleRecordUpdateBatch());
        test.stoptest();
    }

   
}