objects/Account.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <inlineHelpText>Used for Therapak tracking</inlineHelpText>
        <label>Site #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Cancer_Type_Lower_Case__c</fullName>
        <formula>LOWER(Sample_ID__r.Cancer_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hidden field used for email template</inlineHelpText>
        <label>Cancer Type Lower Case</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closest_Trial_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closest Trial Site (Account)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Match Records (Closest Trial Site)</relationshipLabel>
        <relationshipName>Match_Records2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connected_Trial_Site_Address__c</fullName>
        <description>Getting the data from Trial site object on to the Match Record object.</description>
        <formula>Connected_Trial_Site__r.Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Connected Trial Site Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connected_Trial_Site_City__c</fullName>
        <description>Getting the data from Trial site object to the Match Record object.</description>
        <formula>Connected_Trial_Site__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Connected Trial Site City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connected_Trial_Site_State__c</fullName>
        <formula>Connected_Trial_Site__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Connected Trial Site State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connected_Trial_Site_Zip_Code__c</fullName>
        <description>Getting data from Trial Site object on to the Match record object.</description>
        <formula>Connected_Trial_Site__r.Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Connected Trial Site Zip Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connected_Trial_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to trial sites from the same trial.</inlineHelpText>
        <label>Connected Trial Site</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a trial site for this trial.</errorMessage>
            <filterItems>
                <field>$Source.Trial_Name__c</field>
                <operation>equals</operation>
                <valueField>Study_Site__c.Study__r.Id</valueField>
            </filterItems>
            <infoMessage>Use the Search String &apos;*TS-*&apos; to show all trial sites for this match&apos;s trial</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Match Records Connected to this Trial Site</relationshipLabel>
        <relationshipName>Match_Records1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Report_Date__c</fullName>
        <formula>Sample_ID__r.Final_Report_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Final Report Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MD_First_Name__c</fullName>
        <formula>Ordering_Physician_Name__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MD First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD_Last_Name__c</fullName>
        <description>Hidden field to allow non-lookup actions</description>
        <formula>Ordering_Physician_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MD Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Match_Key__c</fullName>
        <label>Match Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordering_Practice_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Ordering Practice Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Match Records for this Practice</relationshipLabel>
        <relationshipName>Match_Records1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_Initials__c</fullName>
        <formula>Patient_ID__r.Patient_Initials__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Patient Initials</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician_Email__c</fullName>
        <formula>Ordering_Physician_Name__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Physician Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician_phone__c</fullName>
        <formula>Ordering_Physician_Name__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Physician phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Link_For_MD_text__c</fullName>
        <formula>&quot;https://portal.guardanthealth.com/r/&quot; &amp; Sample_ID__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portal Link For MD text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Address__c</fullName>
        <formula>Ordering_Practice_Name__r.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Practice Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_City__c</fullName>
        <formula>Ordering_Practice_Name__r.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Practice City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_State__c</fullName>
        <formula>Ordering_Practice_Name__r.BillingState</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Practice State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Zip__c</fullName>
        <formula>Ordering_Practice_Name__r.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Practice Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualifying_Target_Alterations__c</fullName>
        <label>Qualifying Target Alterations</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Code__c</fullName>
        <formula>Trial_Name__r.Trial_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trial Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_label__c</fullName>
        <formula>Trial_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trial label</label>
        <type>Text</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>NCT_Identifier__c</fullName>
        <description>NS:06/12/18 Example:&quot;NCT02428712&quot;</description>
        <label>NCT Identifier</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <description>NS:06/12/18. Example:&quot;A Study of PLX8394 as a Single Agent in Patients With Advanced Unresectable Solid Tumors&quot;</description>
        <label>Study Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trial_Code__c</fullName>
        <label>Trial Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>This Account isn&apos;t a Pharma Site</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Pharma Trial Site</value>
            </filterItems>
            <infoMessage>Must choose Pharma Site</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trial Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trial Site</label>
    <nameField>
        <label>Trial Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MatchRecordSelector.cls
public with sharing class MatchRecordSelector {


    public static Map<String, Match_Record__c> matchRecordsByMatchId(Set<String> matchIds) {
        Map<String, Match_Record__c> result = new Map<String, Match_Record__c>();
        for (Match_Record__c mr : [
                SELECT Id,
                        Match_ID__c,
                        Closest_Trial_Site__c,
                        Trial_Name__c
                FROM Match_Record__c
                WHERE Match_ID__c IN :matchIds
        ]) {
            result.put(mr.Match_ID__c, mr);
        }
        return result;
    }

    public static Match_Record__c queryMatchRecordForYuzu(Id matchRecordId) {
        return [
                SELECT Id,
                        Connected_Trial_Site__c,
                        Match_Key__c,
                        Patient_Initials__c,
                        Qualifying_Target_Alterations__c,
                        Final_Report_Date__c,
                        MD_First_Name__c,
                        MD_Last_Name__c,
                        Physician_Email__c,
                        Physician_phone__c,
                        Ordering_Practice_Name__r.Name,
                        Practice_Address__c,
                        Practice_City__c,
                        Practice_State__c,
                        Practice_Zip__c,
                        Trial_label__c,
                        Connected_Trial_Site__r.Site__r.Name,
                        Connected_Trial_Site_Address__c,
                        Connected_Trial_Site_City__c,
                        Connected_Trial_Site_State__c,
                        Connected_Trial_Site_Zip_Code__c,
                        Cancer_Type_Lower_Case__c,
                        Portal_Link_For_MD_text__c,
                        Trial_Name__r.Study_Title__c,
                        Trial_Name__r.NCT_Identifier__c,
                        Trial_Name__r.Trial_Code__c
                FROM Match_Record__c
                WHERE Id = :matchRecordId
        ];
    }
}