objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_Sample_Update_Processing.cls
@IsTest
public class Test_Sample_Update_Processing {
    
    static testmethod void Sample_Update_Processing() {

        Account[] testAccounts = (Account[])TestFactory.createSObjectList(new Account(),25,true);
        List<Contact> testContacts = new List<Contact>();
        for(Account acc : testAccounts){
            testContacts.add((Contact)TestFactory.createSObject(new Contact(AccountId = acc.Id)));
        }
        insert testContacts;

        List<Guardant_360_Sample__c > lstTRF = new List< Guardant_360_Sample__c>();

        Guardant_360_Sample__c objTRF = null;
        integer intSampleId = 0;
        for(Contact c: testContacts) {
            for(integer i = 0; i < 3; i++) {
                objTRF = new Guardant_360_Sample__c(Name =i.format() + intSampleId.format(), Account__c = c.AccountId, Contact__c = c.id);
                if(i == 0) {
                    objTRF.Date_Received__c = Date.today();
                } else if( i ==1 ) {
                    objTRF.Date_Received__c = Date.today().addDays(2);
                } else {
                    objTRF.Date_Received__c = Date.today().addDays(-2);
                }
                lstTRF.add(objTRF);
                intSampleId++;
            }
        }

        insert lstTRF;
    }
}