objects/Account.object
<CustomObject>
    <fields>
        <fullName>Veeva_ID__c</fullName>
        <externalId>true</externalId>
        <label>Veeva ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Veeva_ID__c</fullName>
        <externalId>true</externalId>
        <label>Veeva ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Veeva_Contact_Affiliation__c.object
<CustomObject>
    <fields>
        <fullName>Entity_VID__c</fullName>
        <label>Entity VID</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_HCO_VID__c</fullName>
        <label>Parent HCO VID</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Veeva_ID__c</fullName>
        <externalId>true</externalId>
        <label>Veeva ID</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <label>Veeva Contact Affiliation</label>
    <nameField>
        <displayFormat>VCA-{0000}</displayFormat>
        <label>Veeva Contact Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veeva Contact Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VeevaContactAffiliationTriggerTest.cls
@isTest
public class VeevaContactAffiliationTriggerTest {
@isTest
    public static void test1(){
        
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Veeva_ID__c = '123456';
        insert acc;
        
        Contact con = new Contact();
        con.LastName = 'Test Contact';
        con.Veeva_ID__c = '789456';
        con.AccountId = acc.Id;
        insert con;
        
        Veeva_Contact_Affiliation__c vcaObj = new Veeva_Contact_Affiliation__c();
        vcaObj.Entity_VID__c = '789456';
        vcaObj.Parent_HCO_VID__c = '123456';
        insert vcaObj;
    }
}