objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Atlantic</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Rocky Mountain</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                    <isActive>false</isActive>
                    <label>Mid-Atlantic</label>
                </value>
                <value>
                    <fullName>Midsouth</fullName>
                    <isActive>false</isActive>
                    <label>Midsouth</label>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                    <isActive>false</isActive>
                    <label>Midwest</label>
                </value>
                <value>
                    <fullName>West</fullName>
                    <isActive>false</isActive>
                    <label>West</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Name__c</fullName>
        <description>Territory name updated through custom code</description>
        <inlineHelpText>Territory name updated through custom code based on active assigned territory</inlineHelpText>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Region__c</fullName>
        <description>Parent Territory Region updated via Apex</description>
        <inlineHelpText>Parent Territory Region updated via Apex</inlineHelpText>
        <label>Territory Region</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Zip_Code__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Zip Code</label>
    <nameField>
        <label>zip code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountTerritoryBatchUpdate.cls
public class AccountTerritoryBatchUpdate implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'select id,Territory_Name__c,Territory_Region__c,BillingPostalCode from account where Account_Type__c =\'Clinical Account US\' and BillingPostalCode != null';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Account> accounts) {
    map<string,Zip_Code__c> zipandTerritoryMap = new map<string,Zip_Code__c>();
    map<string,account> zipAccountMap = new map<string,account>();
    List<account> accList = new List<account>();
    List<account> updateaccList = new List<account>();
    set<string> zipSet = new set<string>();

        for(account acc:accounts){
        accList.add(acc);
        zipAccountMap.put(acc.BillingPostalCode,acc);
        }
        
        if(zipAccountMap.size() > 0){
         zipSet = zipAccountMap.keyset();
        for(Zip_Code__c zip :[select id,Territory__c,Region__c,name from Zip_Code__c where name in:zipSet]){
        zipandTerritoryMap.put(zip.name,zip);
        }
        }
        
        for(account ac : accList){
        if(zipandTerritoryMap.get(ac.BillingPostalCode) != null){
         ac.Territory_Name__c   = zipandTerritoryMap.get(ac.BillingPostalCode).Territory__c;
         ac.Territory_Region__c = zipandTerritoryMap.get(ac.BillingPostalCode).Region__c;
         updateaccList.add(ac);
         }
        }
        
        if(updateaccList.size() > 0){
        update updateaccList;
        }
    }
    public void finish(Database.BatchableContext BC) {
    }

}