objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Delivery_Report_Type__c</fullName>
        <label>Delivery Report Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Fax &amp; Portal</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Courier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Push_to_LabVantage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to push updated account information to LIMS and ERP for previously-qualified (but no longer qualified) accounts. Otherwise, use the &apos;Qualified?&apos; checkbox</description>
        <inlineHelpText>Use this instead of &apos;Qualified?&apos; to push updated account information to LIMS for previously-qualified (but no longer qualified) accounts.</inlineHelpText>
        <label>Push to LabVantage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualified_to_send_to_LIMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger updated field. If there is one contact qualified, Account qualified</description>
        <inlineHelpText>Trigger updated field. If there is one contact qualified, Account qualified</inlineHelpText>
        <label>Qualified to send to LIMS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AdminTriggerToggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Bypass_Affiliation_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to deactivate the Affiliation Triggers</inlineHelpText>
        <label>Bypass Affiliation Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Admin Trigger Toggle</label>
</CustomObject>

objects/Affilation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_in_LIMS__c</fullName>
        <formula>NOT(ISBLANK(Account__r.Sent_to_LIMS__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account in LIMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Affiliated_Fax__c</fullName>
        <label>Affiliated Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delivery_Report_Type__c</fullName>
        <label>Delivery Report Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Courier</fullName>
                </value>
                <value>
                    <fullName>Portal and Fax</fullName>
                </value>
                <value>
                    <fullName>Fax &amp; Portal</fullName>
                    <isActive>false</isActive>
                    <label>Fax &amp; Portal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NY_Sample__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New York Sample</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Treatment__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Needs Treatment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_NPI_No__c</fullName>
        <formula>Contact__r.NPI_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Other NPI No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician_Billing_Type__c</fullName>
        <label>Billing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical Trial : ROW</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial : US</fullName>
                </value>
                <value>
                    <fullName>DirectBill : US</fullName>
                </value>
                <value>
                    <fullName>Distributors : ROW</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Clinical Utility</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - LUNAR</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Pharma</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Proficiency</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Promotional</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Quality Testing</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - ROW</fullName>
                </value>
                <value>
                    <fullName>Financial Indigent</fullName>
                </value>
                <value>
                    <fullName>Medicaid</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma : ROW</fullName>
                </value>
                <value>
                    <fullName>Pharma : US</fullName>
                </value>
                <value>
                    <fullName>Private Insurance/Employee Health Plan</fullName>
                </value>
                <value>
                    <fullName>Private Insurance/Employee Health Plan No OOP</fullName>
                </value>
                <value>
                    <fullName>Research : ROW</fullName>
                </value>
                <value>
                    <fullName>Research : US</fullName>
                </value>
                <value>
                    <fullName>Self-Pay Patient</fullName>
                </value>
                <value>
                    <fullName>Self-Pay Sponsored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_User_Name__c</fullName>
        <label>Portal User Name</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Push_to_Labvantage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Push to Labvantage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualified_AF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Qualified AF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualified_to_send_to_LIMS__c</fullName>
        <formula>Contact__r.Qualified_to_send_to_LIMS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula derived from the Contact&apos;s &apos;Qualified to Send to LIMS&apos; field</inlineHelpText>
        <label>Qualified to send to LIMS</label>
        <type>Checkbox</type>
    </fields>
    <label>Affilation</label>
    <nameField>
        <displayFormat>AF-{000000000}</displayFormat>
        <label>Affilation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affilations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_in_LIMS__c</fullName>
        <formula>NOT(ISBLANK(Account.Sent_to_LIMS__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account in LIMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Delivery_Report_Type__c</fullName>
        <label>Delivery Report Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Courier</fullName>
                </value>
                <value>
                    <fullName>Portal and Fax</fullName>
                </value>
                <value>
                    <fullName>Both Email and Fax</fullName>
                    <isActive>false</isActive>
                    <label>Both Email and Fax</label>
                </value>
                <value>
                    <fullName>Fax &amp; Portal</fullName>
                    <isActive>false</isActive>
                    <label>Fax &amp; Portal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Needs_Treatment__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Needs Treatment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physician_Billing_Type__c</fullName>
        <label>Physician Billing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical Trial : ROW</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial : US</fullName>
                </value>
                <value>
                    <fullName>DirectBill : US</fullName>
                </value>
                <value>
                    <fullName>Distributors : ROW</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Clinical Utility</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - LUNAR</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Pharma</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Proficiency</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Promotional</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Quality Testing</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - ROW</fullName>
                </value>
                <value>
                    <fullName>Financial Indigent</fullName>
                </value>
                <value>
                    <fullName>Medicaid</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma : ROW</fullName>
                </value>
                <value>
                    <fullName>Pharma : US</fullName>
                </value>
                <value>
                    <fullName>Private Insurance/Employee Health Plan</fullName>
                    <default>true</default>
                    <label>Private Insurance/Employee Health Plan</label>
                </value>
                <value>
                    <fullName>Private Insurance/Employee Health Plan No OOP</fullName>
                </value>
                <value>
                    <fullName>Research : ROW</fullName>
                </value>
                <value>
                    <fullName>Research : US</fullName>
                </value>
                <value>
                    <fullName>Self-Pay Patient</fullName>
                </value>
                <value>
                    <fullName>Self-Pay Sponsored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_User_Name__c</fullName>
        <label>Portal User Name</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Push_to_LabVantage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Push to LabVantage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualified_to_send_to_LIMS__c</fullName>
        <formula>Push_to_LabVantage__c || 
Qualified__c ||
Is_Secondary_Physician__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Qualified to send to LIMS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AffiliationActionsTest.cls
@isTest(SeeAllData=false)
public class AffiliationActionsTest {

	@testSetup
	public static void SetupObjects(){
		AdminTriggerToggle__c toggle = new AdminTriggerToggle__c();
		toggle.Bypass_Affiliation_Trigger__c = false;
		insert toggle;

		//Create Account
		Account a1 = (Account) TestFactory.createSObject(new Account(), true);
		//Create Account
		Account a2 = (Account) TestFactory.createSObject(new Account(), true);
		//Create Contact
		Contact c1 = (Contact) TestFactory.createSObject(new Contact(AccountId = a1.Id),true);
		//Create Contact
		Contact c2 = (Contact) TestFactory.createSObject(new Contact(AccountId = a2.Id),true);
		//Create Affiliation
		Affilation__c aff = (Affilation__c) TestFactory.createSObject(new Affilation__c(Account__c = a1.Id, Contact__c = c2.Id),true);
	}
	
	public static testMethod void test_sendNewAffiliationToLims() {
		Map<Id,Affilation__c> affiliationMap = new Map<Id,Affilation__c>([SELECT id
																				,Name
																				,Qualified_to_send_to_LIMS__c
																				,Account_in_LIMS__c
																				,Contact__c
																				,Account__c
																				,Portal_User_Name__c
																				,Delivery_Report_Type__c
																				,Needs_Treatment__c
																				,NY_Sample__c
																				,Physician_Billing_Type__c
																				,Affiliated_Fax__c
                                                                          		,Other_NPI_No__c
                                                                          		,Qualified_AF__c
                                                                          		,Push_to_Labvantage__c
																				,Needs_Long_Report__c
																		  FROM Affilation__c]);
		Test.startTest();
		AffiliationActions.SendChangesToLIMS(null, affiliationMap);
		AffiliationActions.SendChangesToLIMS(affiliationMap, null);
		AffiliationActions.SendChangesToLIMS(affiliationMap, affiliationMap);
		AffiliationActions.BuildPayload(affiliationMap.values()[0],'Test');
		Test.stopTest();
	}
	
	public static testMethod void test_affiliationTriggerHandler() {
		Affilation__c aff = [SELECT id FROM Affilation__c LIMIT 1];
		delete aff;
		undelete aff;
		AffilationTriggerHandler handler = new AffilationTriggerHandler(false,0);
		Boolean isTrigger = handler.IsTriggerContext;
		Boolean isVFPage = handler.IsVisualforcePageContext;
		Boolean isWS = handler.IsWebServiceContext;
		Boolean isAnon = handler.IsExecuteAnonymousContext;

	}	
}