objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Veeva_ID__c</fullName>
        <externalId>true</externalId>
        <label>Veeva ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>if(LEN(Address_Line_1__c)&gt;0, Address_Line_1__c&amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(Address_Line_2__c)&gt;0, Address_Line_2__c&amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c)&gt;0, City__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c)&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Postal_Code__c)&gt;0, Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0, Country__c,&quot;&quot;)</formula>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Contact_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_VID__c</fullName>
        <label>Entity VID</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>GHAD-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Veeva_ID__c</fullName>
        <externalId>true</externalId>
        <label>Veeva ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AddressTriggerHandler.cls
public class AddressTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    
    public AddressTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    public void OnBeforeInsert(Address__c[] newRecords){
        Set<String> entityVID = new Set<String>();
        for(Address__c add : newRecords){
            if(add.Contact__c == null && add.Account__c == null && add.Entity_VID__c <> null){
                entityVID.add(add.Entity_VID__c);
            }
        }
        
        List<Account> accList = [Select ID, Name,Veeva_ID__c from Account where Veeva_ID__c =: entityVID];
        List<Contact> conList = [Select ID, Name,Veeva_ID__c from Contact where Veeva_ID__c =: entityVID];
        
        Map<String, Account> accMap = new Map<String, Account>();
        Map<String, Contact> conMap = new Map<String, Contact>();
        
        for(Account acc : accList){
            accMap.put(acc.Veeva_ID__c, acc);
        }
        
        for(Contact con : conList){
            conMap.put(con.Veeva_ID__c, con);
        }
        
        for(Address__c add : newRecords){
            if(add.Contact__c == null && add.Account__c == null && add.Entity_VID__c <> null){
                Account acc = accMap.get(add.Entity_VID__c);
                Contact con = conMap.get(add.Entity_VID__c);
                
                if(acc != null){
                    add.Account__c = acc.Id;
                }
                else if(con != null){
                    add.Contact__c = con.Id;
                }
            }
        }
    }
}