objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Atlantic</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Rocky Mountain</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                    <isActive>false</isActive>
                    <label>Mid-Atlantic</label>
                </value>
                <value>
                    <fullName>Midsouth</fullName>
                    <isActive>false</isActive>
                    <label>Midsouth</label>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                    <isActive>false</isActive>
                    <label>Midwest</label>
                </value>
                <value>
                    <fullName>West</fullName>
                    <isActive>false</isActive>
                    <label>West</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Integration_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Care_Team_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Care Team Member (Contact Lookup)</inlineHelpText>
        <label>Care Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Integration Tasks (Care Team Member)</relationshipLabel>
        <relationshipName>Account_Integration_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Integration Question (Lookup)</inlineHelpText>
        <label>Integration Question</label>
        <referenceTo>Account_Integration_Tasks_Master__c</referenceTo>
        <relationshipName>Integration_Questions_for_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <inlineHelpText>Physician (Contacts Lookup)</inlineHelpText>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Integration Tasks (Physician)</relationshipLabel>
        <relationshipName>Account_Integration_Tasks1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Integration Tasks</label>
    <nameField>
        <label>Account Integration Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Integration Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Integration_Tasks_Master__c.object
<CustomObject>
    <fields>
        <fullName>Support_Team_Care_Team_Role__c</fullName>
        <label>Support Team/Care Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Team_Member_Roles</valueSetName>
        </valueSet>
    </fields>
    <label>Account Integration Tasks Master</label>
    <nameField>
        <label>Account Integration Tasks Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Integration Tasks Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affilation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Affilation</label>
    <nameField>
        <displayFormat>AF-{000000000}</displayFormat>
        <label>Affilation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affilations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Care_Team_Member_Roles__c</fullName>
        <label>Care Team Member Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Team_Member_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Care_Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Physician Affiliation(Lookup to Physician Contact)</inlineHelpText>
        <label>Physician Affiliation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Care Team Member)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>GRO_Tool__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For an AE to be able to see a contact, the &apos;Region&apos; field on the AE&apos;s user record must = the &apos;Region&apos; field on the Regional Director</description>
        <inlineHelpText>Denotes contacts who are involved in the Account Integration project</inlineHelpText>
        <label>Account Integration Target</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Contact_Type__c</fullName>
        <label>Integration Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Care Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Atlantic</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                    <isActive>false</isActive>
                    <label>Mid-Atlantic</label>
                </value>
                <value>
                    <fullName>Midsouth</fullName>
                    <isActive>false</isActive>
                    <label>Midsouth</label>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                    <isActive>false</isActive>
                    <label>Midwest</label>
                </value>
                <value>
                    <fullName>Rocky Mountain</fullName>
                    <isActive>false</isActive>
                    <label>Rocky Mountain</label>
                </value>
                <value>
                    <fullName>West</fullName>
                    <isActive>false</isActive>
                    <label>West</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Care_Team_Member_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Identifies Patients</fullName>
    </customValue>
    <customValue>
        <fullName>Fills out TRF</fullName>
    </customValue>
    <customValue>
        <fullName>Educates Patient</fullName>
    </customValue>
    <customValue>
        <fullName>Handles Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Draws the Blood</fullName>
    </customValue>
    <customValue>
        <fullName>Sends the Kit</fullName>
    </customValue>
    <customValue>
        <fullName>Gets the Reports</fullName>
    </customValue>
    <masterLabel>Care Team Member Roles</masterLabel>
</GlobalValueSet>

classes/NewContactControllerTest.cls
@isTest
public class NewContactControllerTest {
    @isTest static void setup() {
        
          Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
  
          User usr = new User(LastName = 'LIVESTON',
                     FirstName='JASON',
                     Alias = 'jliv',
                     Email = 'jason.liveston@asdf.com',
                     Username =Math.random()+'@'+Math.random()+'.test',
                     ProfileId = profileId.id,
                     TimeZoneSidKey = 'GMT',
                     LanguageLocaleKey = 'en_US',
                     EmailEncodingKey = 'UTF-8',
                     LocaleSidKey = 'en_US',
                     Region__c ='National'        
                     );
        insert usr;
        
        Account a = new Account();
        a.name = 'Test data';
        a.Region__c ='National';
        a.Account_Type__c ='Clinical Account US';
        a.BillingStreet	='6445 Main StOPC 24';
        a.BillingCountry='US';
        a.BillingCity='Houston';
        a.BillingState	='TX';
        a.BillingPostalCode='77030';
        insert a;
        
        Account_Integration_Tasks_Master__c ac1 = new Account_Integration_Tasks_Master__c();
        ac1.Name='test';
        ac1.Support_Team_Care_Team_Role__c='Sends the kit';
        insert ac1;
        
        Contact con = new Contact();
        con.lastName ='Test';
        con.AccountId=a.Id;
        con.GRO_Tool__c =True;
        con.Integration_Contact_Type__C ='Physician';
        insert con;
        system.debug(con);
        
        Account_Integration_Tasks_Master__c ac = new Account_Integration_Tasks_Master__c();
        ac.Name='test';
        ac.Support_Team_Care_Team_Role__c='Sends the Kit';
        insert ac;
        
  
        
        Account_Integration_Tasks__c at = new Account_Integration_Tasks__c();
        at.Name=ac.name;
        at.Integration_Question__c=ac.Id;
        at.Physician__c =con.Id;
        insert at;
        
        Affilation__c af = new Affilation__c();
        af.Contact__C =Con.Id;
        af.Account__c=a.Id;
        insert af;
        
        NewContactController.groToolRecords(usr.Id);
        NewContactController.getChildRecords(con.Id);
        NewContactController.getCareTeamMemberAccount(con.Id);
        NewContactController.getCareTeamMemberAccountId(con.Id);
        NewContactController.getIntegrationContactType(con.Id);
                 
    }
    @isTest static void setup1(){
        
        Account a = new Account();
        a.name = 'Test data';
        a.Region__c ='National';
        a.Account_Type__c ='Clinical Account US';
        a.BillingStreet	='6445 Main StOPC 24';
        a.BillingCountry='US';
        a.BillingCity='Houston';
        a.BillingState	='TX';
        a.BillingPostalCode='77030';
        insert a;
        
        Contact con = new Contact();
        con.lastName ='Test';
        con.AccountId=a.Id;
        con.GRO_Tool__c =True;
        con.Integration_Contact_Type__C ='Physician';
        insert con;
        
        Contact con1 = new Contact();
        con1.lastName ='Test';
        con1.AccountId=a.Id;
        con1.GRO_Tool__c =True;
        con1.Integration_Contact_Type__C ='Physician';
        con1.Care_Team_Member_Roles__c ='Educates Patient;Draws the Blood';
        
        
        con1.Care_Team_Member__c=con.Id;
        insert con1;
         
    }
}