objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Targeting</fullName>
                </value>
                <value>
                    <fullName>Capabilities</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                </value>
                <value>
                    <fullName>Negotiation</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Guardant_360_Sample__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accession #</label>
        <referenceTo>Guardant_360_Sample__c</referenceTo>
        <relationshipLabel>Cases (Guardant 360 Sample)</relationshipLabel>
        <relationshipName>Cases_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Activity_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New Account Setup</fullName>
                </value>
                <value>
                    <fullName>Add/Edit Users</fullName>
                </value>
                <value>
                    <fullName>Technical Issue</fullName>
                </value>
                <value>
                    <fullName>Reset Password</fullName>
                </value>
                <value>
                    <fullName>User Training</fullName>
                </value>
                <value>
                    <fullName>Add Account ID</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unreported_Sample_Alert_Date__c</fullName>
        <formula>Guardant_360_Sample__r.Unreported_Sample_Alert_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unreported Sample Alert Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT(Account__r.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Report_Date__c</fullName>
        <label>Final Report Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Patient_Test_Count__c</fullName>
        <description>Rank order of sample by the same patient</description>
        <inlineHelpText>This field indicates how many samples (across all request types) were ordered for this Patient when this sample was ordered. This field rolls up the patient’s test count by SFDC Patient ID if available.</inlineHelpText>
        <label>Patient Test Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Date_Received_Contact__c</fullName>
        <label>Previous Date Received (Contact)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Merati</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>SWOG</fullName>
                </value>
                <value>
                    <fullName>Validation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PROCESSED</fullName>
                </value>
                <value>
                    <fullName>CANCELLED</fullName>
                </value>
                <value>
                    <fullName>Corrected</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Reported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Count__c</fullName>
        <description>Rank order of sample by the same physician. Updated via &apos;SampleUpdateTrigger&apos;. See ENT-10645, ENT-8579</description>
        <inlineHelpText>This field indicates how many samples (across all request types) were ordered by this physician  **when this sample was ordered.**  This field rolls up the physician’s test count by NPI number if available.</inlineHelpText>
        <label>Physician Test Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unreported_Sample_Alert_Date__c</fullName>
        <formula>IF(
AND(ISPICKVAL(Request_Type__c,&apos;Pharma&apos;),
LIMS_Project_ID__c &lt;&gt;&apos;G360_NY_2_10&apos;),  
Date_Received__c + 15,
Date_Received__c + 10)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If sample is unreported as of this date, then a process creates a delayed sample case. This date is 10 days after the Date Received for Clinical samples, 15 days after for Pharma samples.</inlineHelpText>
        <label>Unreported Sample Alert Date</label>
        <type>Date</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SampleSelector.cls
public with sharing class SampleSelector {

//    public static String querySamplesNeedingDelayCase() {
//        return 'SELECT Id, Name, Final_Report_Date__c, Unreported_Sample_Alert_Date__c, Contact__c, Account__c, ' +
//                '(SELECT Id FROM Cases_Samples__r WHERE Subject LIKE \'%Delayed%\') ' +
//                'FROM Guardant_360_Sample__c ' +
//                'WHERE Final_Report_Date__c = NULL AND ' +
//                'Unreported_Sample_Alert_Date__c <= TODAY AND ' +
//                'Unreported_Sample_Alert_Date__c >= 2018-01-01 AND ' +
//                '(Request_Type__c = \'Clinical\' OR Request_Type__c = \'Pharma\') ' +
//                'AND Status__c != \'Resolved\' ' +
//                'AND (NOT Account__r.Name LIKE \'%MIRATI%\') ' +
//                'AND Account_Type__c != \'Test\'';
//    }
    public static String querySamplesToSetPreviousSampleDate() {
        return 'SELECT Id, Contact__c, Date_Received__c, Previous_Date_Received_Contact__c ' +
                'FROM Guardant_360_Sample__c ' +
                'WHERE Previous_Date_Received_Contact__c = null ' +
                'AND CreatedDate = LAST_N_DAYS:1';
    }

    public static List<Guardant_360_Sample__c> querySamplesByContact(Set<Id> contactIds) {
        return [
                SELECT Id, Date_Received__c, Previous_Date_Received_Contact__c, Contact__c
                FROM Guardant_360_Sample__c
                WHERE Contact__c IN :contactIds
                ORDER BY Contact__c ASC, Date_Received__c DESC
        ];
    }

    public static Map<Id, Integer> querySampleCountByNpi(Set<Id> npiIds) {
        List<AggregateResult> groupedResults   = [SELECT COUNT(Id) sampleCount, Contact__r.Actual_NPI__c npi FROM Guardant_360_Sample__c WHERE Contact__r.Actual_NPI__c IN : npiIds GROUP BY Contact__r.Actual_NPI__c];
        if (groupedResults == null){
            return null;
        }
        Map<Id,Integer> resultMap = new Map<Id, Integer>();
        for (AggregateResult result : groupedResults) {
            resultMap.put((Id)result.get('npi'), (Integer)result.get('sampleCount'));
        }
        return resultMap;
    }

    public static List<Guardant_360_Sample__c> querySamplesGroupedByNPI(Set<Id> npiIds) {
        return[
                SELECT Id, Date_Received__c, Test_Count__c, Contact__r.Actual_NPI__c
                FROM Guardant_360_Sample__c
                WHERE Contact__r.Actual_NPI__c IN :npiIds
                AND Contact__r.LastName != 'Applicable'
                ORDER BY Contact__r.Actual_NPI__c ASC, Date_Received__c ASC, Name ASC
        ];
    }

    public static List<Guardant_360_Sample__c> querySamplesGroupedByContact(Set<Id> contactIds) {
        List<Guardant_360_Sample__c> sampleList = new List<Guardant_360_Sample__c>();
        System.debug('*** IN querySamplesGroupedByContact');
        //Added by MJ - Production Issue 23 March 2020 - Added the list collection code only, SOQL is as it is
        System.debug('*** contactIds - '+ contactIds);
        System.debug('*** contactIds - '+ contactIds.size());

        if(contactIds != null && !contactIds.isEmpty()){
            sampleList = [
                SELECT Id, Date_Received__c, Test_Count__c, Contact__c
                ,Contact__r.LastName
                FROM Guardant_360_Sample__c
                WHERE Contact__c != :System.Label.GH_Not_Applicable_Contact_ID // MJ 24 March 2020
                AND Contact__c IN :contactIds
                //AND Contact__r.LastName != 'Applicable'//Commented by MJ 24 March 2020, handling this condition in the caller method in for loop
                ORDER BY Contact__c ASC, Date_Received__c ASC, Name ASC
                Limit 50000// MJ 24 March 2020 
        ];
        }
        System.debug('*** sampleList - '+ sampleList);
        System.debug('*** sampleList - '+ sampleList.size());
        return sampleList;
    }

    public static List<Guardant_360_Sample__c> querySamplesGroupedByPatient(Set<Id> patientIds){
        system.debug('@@@@@@@@@@@@@@@@@'+patientIds);
        List<Guardant_360_Sample__c> gsList = new List<Guardant_360_Sample__c>();
        //Added By siva for Null check On March 20,2020

        if(patientIds != null && !patientIds.isEmpty()){
       
             gsList =  [ SELECT Id, Date_Received__c, Test_Count__c, Patient__c, Patient_Test_Count__c
                FROM Guardant_360_Sample__c
                WHERE Patient__c IN :patientIds
                ORDER BY Patient__c ASC, Date_Received__c ASC, Name ASC];
                
        
        }
        return gsList;
        
    }
}