objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Sample_Date__c</fullName>
        <label>Last Sample Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Samples__c</fullName>
        <description>Uses Lookup Rollup Summary to roll up # of samples attributed to this account</description>
        <label>Number of Samples</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unqualified_by_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unqualified by CS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Assistant</fullName>
                </value>
                <value>
                    <fullName>Billing Specialist</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>CEO/COO</fullName>
                </value>
                <value>
                    <fullName>Certified Nurse Assistant</fullName>
                </value>
                <value>
                    <fullName>Clinical Trials Manager</fullName>
                </value>
                <value>
                    <fullName>Cytologist/Cytotechnologist</fullName>
                </value>
                <value>
                    <fullName>General MD</fullName>
                </value>
                <value>
                    <fullName>Genetic Counselor</fullName>
                </value>
                <value>
                    <fullName>Gynecologic Oncologist</fullName>
                </value>
                <value>
                    <fullName>Hematologist</fullName>
                </value>
                <value>
                    <fullName>Hematology/Oncology</fullName>
                </value>
                <value>
                    <fullName>Internist</fullName>
                </value>
                <value>
                    <fullName>Interventional Radiologist</fullName>
                </value>
                <value>
                    <fullName>Lab Manager</fullName>
                </value>
                <value>
                    <fullName>Lab Person</fullName>
                </value>
                <value>
                    <fullName>Medical Assistant</fullName>
                </value>
                <value>
                    <fullName>Medical Oncologist</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Nurse Navigator</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Nursing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Office Staff</fullName>
                </value>
                <value>
                    <fullName>Oncological Urologist</fullName>
                </value>
                <value>
                    <fullName>Oncology Nurse</fullName>
                </value>
                <value>
                    <fullName>Pathologist</fullName>
                </value>
                <value>
                    <fullName>Pediatric Oncologist</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Sample_Date__c</fullName>
        <label>Last Sample Date</label>
        <summarizedField>Guardant_360_Sample__c.Date_Received__c</summarizedField>
        <summaryForeignKey>Guardant_360_Sample__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Marketable_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketable User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Samples__c</fullName>
        <label>Number of Samples</label>
        <summaryForeignKey>Guardant_360_Sample__c.Contact__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unqualified_by_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unqualified by CS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContactSelector.cls
public with sharing class ContactSelector {

//    public static List<Contact> qualifiedContactsSortedByEmailAndSampleCount(Set<String> emails) {
//        return [
//                SELECT Id, Email, Marketable_User__c, Actual_NPI__c
//                FROM Contact
//                WHERE Email IN :emails
//                AND Contact_Role__c IN :ContactService.MARKETABLE_CONTACT_ROLES
//                AND Account_Type__c = 'Clinical Account US'
//                AND (NOT (Number_of_Samples__c > 0 AND Unqualified_by_CS__c = TRUE))
//                ORDER BY Actual_NPI__c ASC, Email ASC, Number_of_Samples__c DESC, Last_Sample_Date__c DESC, CreatedDate DESC
//        ];
//
//        //Possible improvement to this query: Run query above and pull out all NPI numbers, run a second query for all contacts with the same NPI number and re-query larger list and rank
//    }

    public static List<Contact> qualifiedContactsSortedByNpiAndEmailAndSampleCount(Set<String> emails) {
        Set<Id> npiIds = new Set<Id>();
        for (Contact con : [
                SELECT Id, Actual_NPI__c
                FROM Contact
                WHERE Email IN :emails
                AND Contact_Role__c IN :ContactService.MARKETABLE_CONTACT_ROLES
                AND Account_Type__c = 'Clinical Account US'
                AND (NOT (Number_of_Samples__c > 0 AND Unqualified_by_CS__c = TRUE))
        ]) {
            if (con.Actual_NPI__c != null) {
                npiIds.add(con.Actual_NPI__c);
            }
        }
        return [
                SELECT Id, Email, Marketable_User__c, Actual_NPI__c
                FROM Contact
                WHERE (Email IN :emails OR Actual_NPI__c IN :npiIds)
                AND Contact_Role__c IN :ContactService.MARKETABLE_CONTACT_ROLES
                AND Account_Type__c = 'Clinical Account US'
                AND (NOT (Number_of_Samples__c > 0 AND Unqualified_by_CS__c = TRUE))
                ORDER BY Actual_NPI__c ASC, Email ASC, Number_of_Samples__c DESC, Last_Sample_Date__c DESC, CreatedDate DESC
        ];

    }


    public static Map<Id, Id> contactIdsWithNpiNumber(Set<Id> contactIds) {
        Map<Id, Id> contactNPIMap = new Map<Id, Id>();
        for (Contact con : [SELECT Id, Actual_NPI__c FROM Contact WHERE Id IN :contactIds AND Actual_NPI__c != NULL]) {
            contactNPIMap.put(con.Id, con.Actual_NPI__c);
        }
        return contactNPIMap;
    }


}