objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Samples__c</fullName>
        <description>Uses Lookup Rollup Summary to roll up # of samples attributed to this account</description>
        <label>Number of Samples</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unqualified_by_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unqualified by CS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Assistant</fullName>
                </value>
                <value>
                    <fullName>Billing Specialist</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>CEO/COO</fullName>
                </value>
                <value>
                    <fullName>Certified Nurse Assistant</fullName>
                </value>
                <value>
                    <fullName>Clinical Trials Manager</fullName>
                </value>
                <value>
                    <fullName>Cytologist/Cytotechnologist</fullName>
                </value>
                <value>
                    <fullName>General MD</fullName>
                </value>
                <value>
                    <fullName>Genetic Counselor</fullName>
                </value>
                <value>
                    <fullName>Gynecologic Oncologist</fullName>
                </value>
                <value>
                    <fullName>Hematologist</fullName>
                </value>
                <value>
                    <fullName>Hematology/Oncology</fullName>
                </value>
                <value>
                    <fullName>Internist</fullName>
                </value>
                <value>
                    <fullName>Interventional Radiologist</fullName>
                </value>
                <value>
                    <fullName>Lab Manager</fullName>
                </value>
                <value>
                    <fullName>Lab Person</fullName>
                </value>
                <value>
                    <fullName>Medical Assistant</fullName>
                </value>
                <value>
                    <fullName>Medical Oncologist</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Nurse Navigator</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Nursing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Office Staff</fullName>
                </value>
                <value>
                    <fullName>Oncological Urologist</fullName>
                </value>
                <value>
                    <fullName>Oncology Nurse</fullName>
                </value>
                <value>
                    <fullName>Pathologist</fullName>
                </value>
                <value>
                    <fullName>Pediatric Oncologist</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Radiation Oncologist</fullName>
                </value>
                <value>
                    <fullName>Surgical Oncologist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Email_Date__c</fullName>
        <description>Last date this contact was emailed. Determined by activity subject beginning with &apos;Email:&apos; See PB &quot;Task:Last EMail Date&quot;.</description>
        <inlineHelpText>Last date this contact was emailed</inlineHelpText>
        <label>Last Email Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Marketable_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketable User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Samples__c</fullName>
        <label>Number of Samples</label>
        <summaryForeignKey>Guardant_360_Sample__c.Contact__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unqualified_by_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unqualified by CS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContactService.cls
//this class leverages without sharing due to the update of last email date needing to happen on contacts where the email does not always come from the owner
public without sharing class ContactService {
    public List<Contact> unQualifiedContacts;
    public Set<String> qualifiedContactEmails;
    public List<Contact> marketableContactToUpdate;
    public Set<String> qualifiedContactEmailWithDuplicateEmails;
    public static final Set<String> MARKETABLE_CONTACT_ROLES = new Set<String>{
            'Surgical Oncologist',
            'Pediatric Oncologist',
            'Radiation Oncologist',
            'Hematologist',
            'Medical Oncologist',
            'General MD',
            'Gynecologic Oncologist',
            'Nurse Practitioner'
    };

    public void markContactMarketable(List<Contact> contacts){
        unQualifiedContacts = new List<Contact>();
        qualifiedContactEmails = new Set<String>();
        marketableContactToUpdate = new List<Contact>();
        qualifiedContactEmailWithDuplicateEmails = new Set<String>();
        for (Contact contact : contacts) {
            if(contact.Email == null){
                if(contact.Marketable_User__c){
                    contact.Marketable_User__c = false;
                    unQualifiedContacts.add(contact);
                }
                continue; //ignore those without an email
            }
            
             if(contact.Account_Type__c != 'Clinical Account US' && contact.Marketable_User__c){
                    contact.Marketable_User__c = false;
                    unQualifiedContacts.add(contact);
                    continue;
            }
            if(contact.Number_of_Samples__c >0 && contact.Unqualified_by_CS__c){
                if(contact.Marketable_User__c){
                    contact.Marketable_User__c = false;
                    unQualifiedContacts.add(contact);
                }
                continue;
            }
            if(!checkIfQualifiedRole(contact)){
                if(contact.Marketable_User__c){
                    contact.Marketable_User__c = false;
                    unQualifiedContacts.add(contact);
                }
                continue;
            }
            //qualifiedContacts.add(contact);
            qualifiedContactEmails.add(contact.Email);
            //System.debug('qualified emails'+qualifiedContactEmails);
        }
        //get all the contacts with matching emails and sort by email/#samples/sampledate/createdDate. mark first one
        //as marketable contact
        List<Contact> sortedQualifiedContactsByEmail = ContactSelector.qualifiedContactsSortedByNpiAndEmailAndSampleCount(qualifiedContactEmails);
        String currentEmail = '';
        Id currentNPI;
        for (Contact contact : sortedQualifiedContactsByEmail) {
            //System.debug('currentNPI: '+ currentNPI);
            //System.debug('this record NPI: '+ contact.Actual_NPI__c);
            if(contact.Actual_NPI__c != null && contact.Actual_NPI__c == currentNPI){
                contact.Marketable_User__c = false;
                continue;
            }
            if(contact.Email == currentEmail){
                contact.Marketable_User__c = false;
                continue;
            }
            
           
            contact.Marketable_User__c = true;
             if(contact.Email == null){
                contact.Marketable_User__c = false;
                continue;
            }
            currentEmail = contact.Email;
            currentNPI = contact.Actual_NPI__c;
        }
        Log.debug('Contact Count to Update Qualified: '+String.valueOf(sortedQualifiedContactsByEmail.size()));
        Log.debug('Contact Count to Update UnQualified: '+String.valueOf(unQualifiedContacts.size()));
        Database.update(sortedQualifiedContactsByEmail,false);
        Database.update(unQualifiedContacts,false);
    }


    public static Boolean checkIfQualifiedRole(Contact con){
        return MARKETABLE_CONTACT_ROLES.contains(con.Contact_Role__c);
    }


    public static void updateContactEmailDate(Map<Id,Date> contactIdEmailDate){
        List<Contact> contactsToUpdate = new List<Contact>();
        for (Id id : contactIdEmailDate.keySet()) {
            contactsToUpdate.add(new Contact(Id = id, Last_Email_Date__c = contactIdEmailDate.get(id)));
        }
        if(contactsToUpdate.size()>0){
            update contactsToUpdate;
        }
    }

}