objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Sponsor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Biopharma Company that is sponsoring drug study</inlineHelpText>
        <label>Sponsor Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This must be a Biopharma account</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>01234000000HoYe</value>
            </filterItems>
            <infoMessage>Select the sponsoring Biopharma company (must be Biopharma record type)</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Sites</relationshipLabel>
        <relationshipName>Biopharma_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AdminTriggerToggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BypassSampleUpdateTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Sample Update Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Admin Trigger Toggle</label>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>NPI_Matched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPI Matched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NPI_Number__c</fullName>
        <inlineHelpText>Read only field used to sync with LIMS Physicians, domestic and international.</inlineHelpText>
        <label>NPI Number</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_a_Kit_Details__c</fullName>
        <label>Request a Kit Details</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT(Account__r.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LIMS_Project_ID__c</fullName>
        <label>LIMS Project ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Test_Count__c</fullName>
        <description>Rank order of sample by the same patient</description>
        <inlineHelpText>This field indicates how many samples (across all request types) were ordered for this Patient when this sample was ordered. This field rolls up the patient’s test count by SFDC Patient ID if available.</inlineHelpText>
        <label>Patient Test Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Date_Received_Contact__c</fullName>
        <label>Previous Date Received (Contact)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Test_Count__c</fullName>
        <description>Rank order of sample by the same physician. Updated via &apos;SampleUpdateTrigger&apos;. See ENT-10645, ENT-8579</description>
        <inlineHelpText>This field indicates how many samples (across all request types) were ordered by this physician  **when this sample was ordered.**  This field rolls up the physician’s test count by NPI number if available.</inlineHelpText>
        <label>Physician Test Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LIMS_Project_ID__c.object
<CustomObject>
    <fields>
        <fullName>LIMS_Project_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External ID from LIMS. Duplicate values not allowed.</inlineHelpText>
        <label>Project ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sponsor_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sponsor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Project IDs</relationshipLabel>
        <relationshipName>LIMS_Project_IDs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project ID</label>
    <nameField>
        <label>ProjectID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NPI_Records__c.object
<CustomObject>
    <fields>
        <fullName>NPI_Number__c</fullName>
        <externalId>true</externalId>
        <label>NPI Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NPI Record</label>
    <nameField>
        <label>NPI Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPI Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Patient__c.object
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SampleServiceTest.cls
@IsTest(SeeAllData=false)
public with sharing class SampleServiceTest {


    @TestSetup
    public static void setupObjects(){
        AdminTriggerToggle__c toggle = new AdminTriggerToggle__c();
        toggle.BypassSampleUpdateTrigger__c = false;
        insert toggle;

        //Create Account
        Account a1 = (Account) TestFactory.createSObject(new Account(Account_Type__c = 'Clinical Account US'), true);
        //Create Contact
        Contact c1 = (Contact) TestFactory.createSObject(new Contact(AccountId = a1.Id),true);
        //Create Samples
        Guardant_360_Sample__c[] samples = (Guardant_360_Sample__c[]) TestFactory.createSObjectList(new Guardant_360_Sample__c(Contact__c = c1.Id, Account__c = a1.Id),10);
        for (Integer i = 0; i < samples.size(); i++) {
            Guardant_360_Sample__c sample = samples.get(i);
            sample.Date_Received__c = Date.today() - i;
        }
        insert samples;
    }

    
    @IsTest
    public static void testProcessNewSamples(){
            Account a1 = (Account) TestFactory.createSObject(new Account(Account_Type__c = 'Clinical Account US'), true);
             NPI_Records__c np = new NPI_Records__c(name='1234567890',NPI_Number__c='1234567890');
      insert np;

        Contact con = (Contact)TestFactory.createSObject(new Contact(
                LastName = 'Test01',
                NPI_Matched__c = false,
                NPI_Number__c = '1234567890',Actual_NPI__c=np.id,
                AccountId = a1.Id,
                Request_a_Kit_Details__c = 'chandra1112s112,kumar,7657889567,chandra111@gmail.com, younesh,RY,younesh123@gmail.com,practiveEmail,morabadi,ranchi,jharkhand,01234,BREAST CANCER'
        ),true);
                Guardant_360_Sample__c[] samples = (Guardant_360_Sample__c[]) TestFactory.createSObjectList(new Guardant_360_Sample__c(Contact__c = con.Id, Account__c = a1.Id),10);

       test.starttest();
     
       set<id> ss= new set<id>{};
        List<Guardant_360_Sample__c> samples1 = querySamples();
        SampleService.processNewSamples(samples1);
        SampleSelector.querySampleCountByNpi(new set<id>{np.id});
        test.stoptest();
    }

    @IsTest
    public static void testRankSamples(){
        List<Guardant_360_Sample__c> samples = querySamples();
        SampleService.rankSamples(samples);
    }

    @IsTest
    public static void testRankSamples2(){
        List<Guardant_360_Sample__c> samples = querySamples();
        SampleService.rankSamples(new Map<Id,Guardant_360_Sample__c>(samples),new Map<Id,Guardant_360_Sample__c>(samples));
    }

    @IsTest
    public static void testRankSamplesBySinglePhysician(){
        Id contactId = [SELECT Id FROM Contact LIMIT 1].Id;
        SampleService.rankSamplesBySinglePhysician(contactId);
    }
    
     @IsTest
    public static void testRankSamplesBySinglePhysician6(){
    Account a1 = (Account) TestFactory.createSObject(new Account(Account_Type__c = 'Clinical Account US'), true);
        //Create Contact
    Contact c1 = (Contact) TestFactory.createSObject(new Contact(AccountId = a1.Id),true);
    //Create Samples
    LIMS_Project_ID__c   lp= new LIMS_Project_ID__c( LIMS_Project_ID__c ='1234',Sponsor_Account__c =a1.id) ;
   insert lp;
   Test.startTest();
   LIMS_Project_ID__c   lp1= new LIMS_Project_ID__c( LIMS_Project_ID__c ='2134',Sponsor_Account__c =a1.id) ;
   insert lp1;
    Guardant_360_Sample__c sample = new Guardant_360_Sample__c(LIMS_Project_ID__c='1234',Contact__c = c1.Id, Account__c = a1.Id);
  insert sample;
  Guardant_360_Sample__c gs = new Guardant_360_Sample__c(id=sample.id, LIMS_Project_ID__c = '2134');
 
  update gs;
     Test.stopTest();

   
   }

    @IsTest
    public static void testSetPreviousSampleDate(){
        Guardant_360_Sample__c[] samples = Database.query(SampleSelector.querySamplesToSetPreviousSampleDate());
        Test.startTest();
        SampleService.setPreviousSampleDate(samples);
        Test.stopTest();
        samples = [SELECT Id, Date_Received__c, Previous_Date_Received_Contact__c FROM Guardant_360_Sample__c ORDER BY Date_Received__c DESC ];

        System.assertEquals(Date.today()-1, samples[0].Previous_Date_Received_Contact__c);
        delete samples;
        SampleTriggerHandler sampl = new SampleTriggerHandler(true,1);
        sampl.OnBeforeUpdate(new List<Guardant_360_Sample__c>(),new List<Guardant_360_Sample__c>(),new Map<id,Guardant_360_Sample__c>(),new Map<id,Guardant_360_Sample__c>());
        sampl.OnBeforeInsert(new List<Guardant_360_Sample__c>());
        Boolean b = sampl.IsTriggerContext;
        Boolean c =sampl.IsExecuteAnonymousContext;
        Boolean d =sampl.IsWebServiceContext;
        Boolean e =sampl.IsVisualforcePageContext;
    }

    private static List<Guardant_360_Sample__c> querySamples(){
        return [SELECT Id, Contact__c, Patient__c, Test_Count__c, Patient_Test_Count__c FROM Guardant_360_Sample__c];
    }
}