objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>NPI_Number__c</fullName>
        <inlineHelpText>Read only field used to sync with LIMS Physicians, domestic and international.</inlineHelpText>
        <label>NPI Number</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NPI_Records__c.object
<CustomObject>
    <fields>
        <fullName>NPI_Number__c</fullName>
        <externalId>true</externalId>
        <label>NPI Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Total_Samples__c</fullName>
        <description>Updated via Apex Class NpiService</description>
        <label>Total Samples</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NPI Record</label>
    <nameField>
        <label>NPI Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPI Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NpiServiceTest.cls
@IsTest(SeeAllData=false)
public with sharing class NpiServiceTest {

    @TestSetup
    private static void setupObjects(){
        //Create Account
        Account a1 = (Account) TestFactory.createSObject(new Account(), true);
        //Create NPI
        NPI_Records__c npi = (NPI_Records__c)TestFactory.createSObject(new NPI_Records__c(NPI_Number__c = '12345'),true);
        //Create Contact
        Contact c1 = (Contact) TestFactory.createSObject(new Contact(AccountId = a1.Id, Actual_NPI__c = npi.Id),true);
    }

    @IsTest
    private static void testUpdateTotalSamplesNoSamples() {
        NpiService.updateTotalSamples(getNpiRecords().keySet());
        for (NPI_Records__c npiRecord : getNpiRecords().values()) {
            System.assertEquals(null,npiRecord.Total_Samples__c);
        }
    }

    @IsTest
    private static void testUpdateTotalSamples() {
        //Get Contact
        Contact con = [SELECT Id, AccountId FROM Contact LIMIT 1];
        //Create Samples
        TestFactory.createSObjectList(new Guardant_360_Sample__c(Contact__c = con.Id, Account__c = con.AccountId),20,true);
        NpiService.updateTotalSamples(getNpiRecords().keySet());
        for (NPI_Records__c npiRecord : getNpiRecords().values()) {
            System.assertEquals(20,npiRecord.Total_Samples__c);
        }
    }

    private static Map<Id,NPI_Records__c> getNpiRecords(){
        return new Map<Id,NPI_Records__c>([SELECT Id, Total_Samples__c FROM NPI_Records__c]);
    }
}