objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Integration_Target__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is checked, this account has a contact or affiliation that is part of the Account Integration Target program</inlineHelpText>
        <label>Account Integration Target</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Atlantic</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Rocky Mountain</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                    <isActive>false</isActive>
                    <label>Mid-Atlantic</label>
                </value>
                <value>
                    <fullName>Midsouth</fullName>
                    <isActive>false</isActive>
                    <label>Midsouth</label>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                    <isActive>false</isActive>
                    <label>Midwest</label>
                </value>
                <value>
                    <fullName>West</fullName>
                    <isActive>false</isActive>
                    <label>West</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Integration_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Care_Team_Member_Role__c</fullName>
        <label>Care Team Member Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Team_Member_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Care_Team_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Care Team Member (Contact Lookup)</inlineHelpText>
        <label>Care Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Integration Tasks (Care Team Member)</relationshipLabel>
        <relationshipName>Account_Integration_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integration_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Integration Question (Lookup)</inlineHelpText>
        <label>Integration Question</label>
        <referenceTo>Account_Integration_Tasks_Master__c</referenceTo>
        <relationshipName>Integration_Questions_for_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mark_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mark Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physician__c</fullName>
        <inlineHelpText>Physician (Contacts Lookup)</inlineHelpText>
        <label>Physician</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Integration Tasks (Physician)</relationshipLabel>
        <relationshipName>Account_Integration_Tasks1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Integration Tasks</label>
    <nameField>
        <label>Account Integration Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Integration Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_Integration_Tasks_Master__c.object
<CustomObject>
    <fields>
        <fullName>Support_Team_Care_Team_Role__c</fullName>
        <label>Support Team/Care Team Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Team_Member_Roles</valueSetName>
        </valueSet>
    </fields>
    <label>Account Integration Tasks Master</label>
    <nameField>
        <label>Account Integration Tasks Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Integration Tasks Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Affilation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Affilation</label>
    <nameField>
        <displayFormat>AF-{000000000}</displayFormat>
        <label>Affilation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affilations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Integration_Target__c</fullName>
        <defaultValue>false</defaultValue>
        <description>DEPRECATED. Use &apos;Account Integration Target&apos; (GRO_Tool__c) instead.</description>
        <label>Acct Integration Target</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Care_Team_Member_Roles__c</fullName>
        <label>Care Team Member Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Care_Team_Member_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Care_Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Physician Affiliation(Lookup to Physician Contact)</inlineHelpText>
        <label>Physician Affiliation</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Care Team Member)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>GRO_Tool__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For an AE to be able to see a contact, the &apos;Region&apos; field on the AE&apos;s user record must = the &apos;Region&apos; field on the Regional Director</description>
        <inlineHelpText>Denotes contacts who are involved in the Account Integration project</inlineHelpText>
        <label>Account Integration Target</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integrated_formula__c</fullName>
        <formula>IF(GRO_Tool__c=TRUE, 
Integration_Questions_Completed__c/Integration_Questions_Total__c, 
(IF(NOT(ISBLANK(Care_Team_Member__c)),Care_Team_Member__r.Integration_Questions_Completed__c/Care_Team_Member__r.Integration_Questions_Total__c, 
0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Integrated %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Integration_Contact_Type__c</fullName>
        <label>Integration Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Care Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Atlantic</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                    <isActive>false</isActive>
                    <label>Mid-Atlantic</label>
                </value>
                <value>
                    <fullName>Midsouth</fullName>
                    <isActive>false</isActive>
                    <label>Midsouth</label>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                    <isActive>false</isActive>
                    <label>Midwest</label>
                </value>
                <value>
                    <fullName>Rocky Mountain</fullName>
                    <isActive>false</isActive>
                    <label>Rocky Mountain</label>
                </value>
                <value>
                    <fullName>West</fullName>
                    <isActive>false</isActive>
                    <label>West</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Care_Team_Member_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Identifies Patients</fullName>
    </customValue>
    <customValue>
        <fullName>Fills out TRF</fullName>
    </customValue>
    <customValue>
        <fullName>Educates Patient</fullName>
    </customValue>
    <customValue>
        <fullName>Handles Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Draws the Blood</fullName>
    </customValue>
    <customValue>
        <fullName>Sends the Kit</fullName>
    </customValue>
    <customValue>
        <fullName>Gets the Reports</fullName>
    </customValue>
    <masterLabel>Care Team Member Roles</masterLabel>
</GlobalValueSet>

classes/NewContactController.cls
public with sharing class NewContactController {
    @AuraEnabled(cacheable=true)
    public static List<Account_Integration_Tasks__c> getChildRecords(String supervisor) {
		System.debug('Sup >> '+supervisor);
        List<Contact> cList = new List<Contact>();
        cList = [SELECT Id, Integration_Contact_Type__c, Care_Team_Member_Roles__c  FROM Contact WHERE Id =: supervisor];
        
        List<Account_Integration_Tasks__c> actList = new List<Account_Integration_Tasks__c>();
        
		List<Account_Integration_Tasks__c> actListFinal = new List<Account_Integration_Tasks__c>();
        if( cList.size() > 0 ) {
            if( cList[0].Integration_Contact_Type__c == 'Care Team Member' ) {
                actList = [SELECT Id, Physician__c, Care_Team_Member__r.Care_Team_Member_Roles__c, Care_Team_Member__c,Integration_Question__r.Support_Team_Care_Team_Role__c, Date_Completed__c, Mark_Completed__c, Name FROM Account_Integration_Tasks__c WHERE Care_Team_Member__c =: supervisor];
                for( Account_Integration_Tasks__c acc : actList ) {
                    if( cList[0].Care_Team_member_Roles__c.contains(acc.Integration_Question__r.Support_Team_Care_Team_Role__c ) ) {
                        actListFinal.add(acc);
                    }
                }
            }
            else{
                actList = [SELECT Id, Physician__c, Care_Team_Member__r.Care_Team_Member_Roles__c, Care_Team_Member__c,Integration_Question__r.Support_Team_Care_Team_Role__c, Date_Completed__c, Mark_Completed__c, Name FROM Account_Integration_Tasks__c WHERE Physician__c =: supervisor];
                actListFinal.addAll(actList);
            }
        }
        system.debug('actListFinal>>'+actListFinal);
        return actListFinal;
        // return [SELECT Id, Care_Team_Member__c, Care_Team_Member_Role__c, Date_Completed__c, Mark_Completed__c, Name FROM Account_Integration_Tasks__c WHERE Physician__c =: supervisor];
    }
    @AuraEnabled(cacheable=true)
    public static List<Object>groToolRecords(String filter) {
        String usersRegion;
        usersRegion = [SELECT Region__c FROM User WHERE Id =: filter].Region__c;
        // return [SELECT Id, Name, Integrated_formula__c, Account.Name  FROM Contact WHERE GRO_Tool__c = true AND Region__c =: usersRegion AND Integration_Contact_Type__C = 'Physician'];
        Map<String, Contact> accountContactMap = new Map<String, Contact>();
        Map<Id, String> contactVsAffilation = new Map<Id, String>();
        List<Contact> contactList = new List<Contact>();
        List<Account> accountList = new List<Account>();
        List<Affilation__c> affilationList = new List<Affilation__c>();
        List<Group> groupList = new List<Group>();
        groupList = [SELECT Id, Name FROM Group WHERE DeveloperName='GRO_Leadership'];
        if( groupList.size() > 0 ) {
            List<GroupMember> groupMemberList = new List<GroupMember>();
            groupMemberList = [SELECT Id, UserOrGroupId FROM GroupMember WHERE GroupId =: groupList[0].Id];
            if( groupMemberList.size() > 0 ) {
                List<String> groupedUser = new List<String>();
                for ( GroupMember gm : groupMemberList ) {
                    groupedUser.add(gm.UserOrGroupId);
                }
                if( groupedUser.contains(UserInfo.getUserId()) ) {
                    contactList = [SELECT Id, Name, Account.Name, (SELECT Account__c, Account__r.Name FROM Affilations__r where Account__r.Account_Integration_Target__C = true), Integrated_formula__c, AccountId, Account.Account_Integration_Target__c  FROM Contact WHERE GRO_Tool__c = true AND Integration_Contact_Type__C = 'Physician'];
                }
                else
                {
                    contactList = [SELECT Id, Name, Account.Name, (SELECT Account__c, Account__r.Name FROM Affilations__r where Account__r.Account_Integration_Target__C = true), Integrated_formula__c, AccountId, Account.Account_Integration_Target__c  FROM Contact WHERE GRO_Tool__c = true AND Region__c =: usersRegion AND Integration_Contact_Type__C = 'Physician'];
                }
            }
            else
            {
                contactList = [SELECT Id, Name, Account.Name, (SELECT Account__c, Account__r.Name FROM Affilations__r where Account__r.Account_Integration_Target__C = true), Integrated_formula__c, AccountId, Account.Account_Integration_Target__c  FROM Contact WHERE GRO_Tool__c = true AND Region__c =: usersRegion AND Integration_Contact_Type__C = 'Physician'];
            }
        }
        else
        {
            contactList = [SELECT Id, Name, Account.Name, (SELECT Account__c, Account__r.Name FROM Affilations__r where Account__r.Account_Integration_Target__C = true), Integrated_formula__c, AccountId, Account.Account_Integration_Target__c  FROM Contact WHERE GRO_Tool__c = true AND Region__c =: usersRegion AND Integration_Contact_Type__C = 'Physician'];
        }
        System.debug('CT >> '+contactList);
        System.debug('CT Size >> '+contactList.size());
        if( contactList.size() > 0 ) {
            for( Contact c : contactList ) {
                String accountSet;
                if( c.Account.Account_Integration_Target__c ) {
                 	accountSet = c.Account.Name;
                }
                else
                {
                    if( c.Affilations__r.size() > 0 && accountSet == null ) {
                        for( Affilation__c a : c.Affilations__r ) {
                            accountSet = a.Account__r.Name;
                            break;
                        }
                    }   
                }
                contactVsAffilation.put(c.Id, accountSet);
            }
        }
        List<Object> selfCreatedList = new List<Object>();
        if( contactList.size() > 0 ) {
            for( Contact c : contactList ) {
                GROClassCustom gcc = new GROClassCustom();
                gcc.id = c.Id;
                gcc.Name = c.Name;
                gcc.percentage = c.Integrated_formula__C;
                gcc.widthPercentage = 'width: '+c.Integrated_formula__C+'%;';
                gcc.AccountName = contactVsAffilation.get(c.Id);
                selfCreatedList.add(JSON.deserializeUntyped(JSON.serialize(gcc)));
            }
        }
        return selfCreatedList;
    }
    @AuraEnabled(cacheable=true)
    public static List<Contact>getChildContacts(String filter) {
          return [SELECT Id, Name, Care_Team_Member_Roles__c FROM Contact WHERE Care_Team_Member__c =: filter];
    }
    @AuraEnabled(cacheable=true)
    public static String getCareTeamMemberAccountId(String filter) {
        String finalAccount = '';
        String finalAccountName = '';
        Set<String> accounts = new Set<String>();
		List<Contact> contactList = new List<Contact>();
        List<Account> accountList = new List<Account>();
        List<Affilation__c> affilationList = new List<Affilation__c>();
        affilationList = [SELECT Account__c FROM Affilation__c WHERE Contact__c =: filter];
        System.debug('Aff List >>'+affilationList);
        if( affilationList.size() > 0 ) {
            for( Affilation__c aff : affilationList ) {
                accounts.add(aff.Account__c);
            }
        }
        contactList = [SELECT AccountId FROM Contact WHERE Id =: filter];
        if( contactList.size() > 0 ) {
            for( Contact c : contactList ) {
                accounts.add(c.AccountId);
            }
        }
        if( accounts.size() > 0 ) {
            accountList = [SELECT Id, Account_Integration_Target__c FROM Account WHERE Id IN :accounts];
            System.debug('Acc List >> '+accountList);
            if( accountList.size() > 0 ) {
                for( Account acc : accountList ) {
                    if( acc.Account_Integration_Target__c ) {
                        finalAccount = acc.Id;
                    }
                }
            }
        }
        if( finalAccount != '' ) {
            finalAccountName = [SELECT Id FROM Account WHERE Id =: finalAccount].Id;
        }
		return finalAccountName;
    }
    @AuraEnabled(cacheable=true)
    public static String getCareTeamMemberAccount(String filter) {
        String finalAccount = '';
        String finalAccountName = '';
        Set<String> accounts = new Set<String>();
		List<Contact> contactList = new List<Contact>();
        List<Account> accountList = new List<Account>();
        List<Affilation__c> affilationList = new List<Affilation__c>();
        affilationList = [SELECT Account__c FROM Affilation__c WHERE Contact__c =: filter];
        System.debug('Aff List >>'+affilationList);
        if( affilationList.size() > 0 ) {
            for( Affilation__c aff : affilationList ) {
                accounts.add(aff.Account__c);
            }
        }
        contactList = [SELECT AccountId FROM Contact WHERE Id =: filter];
        if( contactList.size() > 0 ) {
            for( Contact c : contactList ) {
                accounts.add(c.AccountId);
            }
        }
        if( accounts.size() > 0 ) {
            accountList = [SELECT Id, Account_Integration_Target__c FROM Account WHERE Id IN :accounts];
            System.debug('Acc List >> '+accountList);
            if( accountList.size() > 0 ) {
                for( Account acc : accountList ) {
                    if( acc.Account_Integration_Target__c ) {
                        finalAccount = acc.Id;
                    }
                }
            }
        }
        if( finalAccount != '' ) {
            finalAccountName = [SELECT Name FROM Account WHERE Id =: finalAccount].Name;
        }
		return finalAccountName;
    }
    @AuraEnabled(cacheable=true)
    public static String getIntegrationContactType(String filter) {
        String integrationContactType = '';
        String findType = [SELECT Integration_Contact_Type__c FROM Contact WHERE Id =: filter].Integration_Contact_Type__c;
        if( findType != null ) {
            integrationContactType = findType;
        }
        return integrationContactType;
    }
    @AuraEnabled(cacheable=true)
    public static List<Task> getActivityTask(String filter) {
        return [SELECT Id, Subject, Priority, Status, ActivityDate, CreatedDate FROM Task WHERE WhoId =: filter];
    }
    public class GROClassCustom {
        public Id Id;
        public String Name;
        public String AccountName;
        public Decimal percentage;
        public String widthPercentage;
    }
}