objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>First_Sample_Date__c</fullName>
        <label>First Sample Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Sample_Date__c</fullName>
        <label>Last Sample Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Samples__c</fullName>
        <description>Uses Lookup Rollup Summary to roll up # of samples attributed to this account</description>
        <label>Number of Samples</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>First_Sample_Date__c</fullName>
        <label>First Sample Date</label>
        <summarizedField>Guardant_360_Sample__c.Date_Received__c</summarizedField>
        <summaryForeignKey>Guardant_360_Sample__c.Contact__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Sample_Date__c</fullName>
        <label>Last Sample Date</label>
        <summarizedField>Guardant_360_Sample__c.Date_Received__c</summarizedField>
        <summaryForeignKey>Guardant_360_Sample__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Sample__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Sample</label>
        <referenceTo>Guardant_360_Sample__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Samples__c</fullName>
        <label>Number of Samples</label>
        <summaryForeignKey>Guardant_360_Sample__c.Contact__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_Date_Received_Contact__c</fullName>
        <label>Previous Date Received (Contact)</label>
        <type>Date</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SampleUpdateProcessing.cls
public class SampleUpdateProcessing {
 
    public static void setRollups(List<Guardant_360_Sample__c> TriggerNew) {
        //Set<Id> setAccountId = new Set<Id>();
        Set<Id> contactIdSet = new Set<Id>();

        for(Guardant_360_Sample__c trf: TriggerNew) {
            //setAccountId.add(trf.Account__c);
            contactIdSet.add(trf.Contact__c);
        }

        //Set Latest Sample on Contact Last_Sample__c

        //Query all the contacts and latest samples
        List<Contact> contactList = [SELECT id, (
                                                SELECT id , Date_Received__c 
                                                FROM Guardant_360_Samples__r 
                                                ORDER BY Date_Received__c DESC
                                                LIMIT 1)
                                    FROM Contact
                                    WHERE Id in:contactIdSet];

        for(Contact c : contactList){
            c.Last_Sample__c = c.Guardant_360_Samples__r[0].id;
        }
        update contactList;


        // Set rollup values on Account

        //Account objAcc;
        //AggregateResult[] agrSample = [SELECT Account__c, MIN(Date_Received__c), MAX(Date_Received__c), COUNT(Id) 
        //                                FROM Guardant_360_Sample__c WHERE Account__c IN :setAccountId GROUP BY Account__c];
        
        //List<Account> updAcc = new List<Account>();
       
        //for(AggregateResult ar: agrSample) {
        //    objAcc = new Account(Id = (id)ar.get('Account__c'),
        //                         First_Sample_Date__c = date.valueOf(ar.get('expr0')),
        //                         Last_Sample_Date__c = date.valueOf(ar.get('expr1')),
        //                         Number_of_Samples__c = integer.valueOf(ar.get('expr2')));
        //    updAcc.add(objAcc);

        //}

        //update updAcc;
    }


    public static void setPrevious(List<Guardant_360_Sample__c> TriggerNew) {
        Set<Id> setContactId = new Set<Id>();     

        for(Guardant_360_Sample__c trf: TriggerNew) {
            setContactId.add(trf.Contact__c);
        }

        // Set previous sample date 

        List<Guardant_360_Sample__c> lstTRF = [select Id, Contact__c, Date_Received__c from Guardant_360_Sample__c
                                               where Contact__c IN :setContactId order by Date_Received__c ASC];
        
        Date prevDate = null;
        boolean prevDateIsSet = false;
        Guardant_360_Sample__c objTRF = null;

        List<Guardant_360_Sample__c> updTRF = new List<Guardant_360_Sample__c>();

        for(Guardant_360_Sample__c trf: TriggerNew) {
        
            //find previous sample date
            for(Guardant_360_Sample__c prevtrf: lstTRF) {
                if(prevtrf.Contact__c == trf.Contact__c && prevtrf.Date_Received__c < trf.Date_Received__c) {
                    trf.Previous_Date_Received_Contact__c = prevtrf.Date_Received__c;
                 }
            }
        }
    }
}