objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Client_Notes__c</fullName>
        <label>Client Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Signature__c</fullName>
        <label>Custom Signature</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Generic Signature</fullName>
                    <default>true</default>
                    <label>Generic Signature</label>
                </value>
                <value>
                    <fullName>Tim Schmidt, MD, PhD</fullName>
                </value>
                <value>
                    <fullName>Jason Zhu, MD</fullName>
                </value>
                <value>
                    <fullName>Maya Kotas, MD, PhD</fullName>
                </value>
                <value>
                    <fullName>Shawn Becker, MD</fullName>
                </value>
                <value>
                    <fullName>Rick Lanman, MD</fullName>
                </value>
                <value>
                    <fullName>Sam Sun, MD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Enrolled__c</fullName>
        <label>Date Enrolled/Prescribed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Ineligible__c</fullName>
        <label>Date Ineligible</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Referred__c</fullName>
        <label>Date Informed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_1st_Contact__c</fullName>
        <label>Date of 1st Contact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_Failed_Screening__c</fullName>
        <label>Date of Failed Screening</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_Last_Contact__c</fullName>
        <label>Date of Last Contact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Guardant Outreach</fullName>
                </value>
                <value>
                    <fullName>Pharma Outreach</fullName>
                    <label>Pharma/Site Outreach</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                    <label>Enrolled/Prescribed</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enrollment_Sub_Status__c</fullName>
        <label>Referral Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Enrollment_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Pharma</fullName>
                </value>
                <value>
                    <fullName>Accepted by Pharma</fullName>
                </value>
                <value>
                    <fullName>Emailed</fullName>
                </value>
                <value>
                    <fullName>Ready For Outreach</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Left Message</fullName>
                </value>
                <value>
                    <fullName>Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Via Match Program</fullName>
                </value>
                <value>
                    <fullName>Patient Lost to Follow Up</fullName>
                </value>
                <value>
                    <fullName>Provider Refusal</fullName>
                </value>
                <value>
                    <fullName>Patient Refusal</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Trial Change</fullName>
                </value>
                <value>
                    <fullName>Rejected by Pharma</fullName>
                </value>
                <value>
                    <fullName>Newer Test Results Available</fullName>
                </value>
                <value>
                    <fullName>Exhausted Follow-Up</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pending GH Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Guardant_Notes__c</fullName>
        <label>External Guardant Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Match_API_Update__c</fullName>
        <label>Last Match API Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Match_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Match_Priority__c</fullName>
        <label>Match Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Match_Status__c</fullName>
        <label>Match Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permission_to_Connect_with_Pharma__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Permission to Connect with Pharma?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_Sample_ID__c</fullName>
        <label>Portal Sample ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referred__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, a referral letter will be sent to MD</inlineHelpText>
        <label>Informed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_POD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send POD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Show to Customer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Status_Reason__c</fullName>
        <label>Sub-Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Enrollment_Sub_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>On Treatment</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                    <label>On Trial</label>
                </value>
                <value>
                    <fullName>Death</fullName>
                </value>
                <value>
                    <fullName>Too Ill/Hospice</fullName>
                </value>
                <value>
                    <fullName>Prior Treatment</fullName>
                </value>
                <value>
                    <fullName>Failed Pharma Screening</fullName>
                    <label>Failed Trial Screening</label>
                </value>
                <value>
                    <fullName>Travel</fullName>
                    <label>Travel Limitations</label>
                </value>
                <value>
                    <fullName>Research Objection</fullName>
                </value>
                <value>
                    <fullName>No Longer Enrolling</fullName>
                </value>
                <value>
                    <fullName>Match Criteria Changed</fullName>
                </value>
                <value>
                    <fullName>MD Engaged</fullName>
                </value>
                <value>
                    <fullName>MD Non-Engaged</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Left Message</fullName>
                </value>
                <value>
                    <fullName>Sent Email</fullName>
                </value>
                <value>
                    <fullName>Future Consideration - On Treatment</fullName>
                </value>
                <value>
                    <fullName>Future Consideration - On Trial</fullName>
                </value>
                <value>
                    <fullName>Future Consideration - Other</fullName>
                </value>
                <value>
                    <fullName>Referred to Trial Site</fullName>
                </value>
                <value>
                    <fullName>Pending Prescription</fullName>
                </value>
                <value>
                    <fullName>Undergoing Screening</fullName>
                </value>
                <value>
                    <fullName>Aware of Trial</fullName>
                    <label>Aware</label>
                </value>
                <value>
                    <fullName>Insurance Coverage</fullName>
                </value>
                <value>
                    <fullName>Do Not Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1st_Paragraph__c</fullName>
        <label>1st Paragraph</label>
        <type>TextArea</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POD__c.object
<CustomObject>
    <description>Proof of Delivery</description>
    <fields>
        <fullName>Match_ID__c</fullName>
        <formula>Match_Record__r.Match_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Record__c</fullName>
        <label>Match Record</label>
        <referenceTo>Match_Record__c</referenceTo>
        <relationshipLabel>PODs</relationshipLabel>
        <relationshipName>PODs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>POD</label>
    <nameField>
        <displayFormat>POD-{0000}</displayFormat>
        <label>POD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PODs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MatchRecordTriggerHandlerTest.cls
@IsTest
private class MatchRecordTriggerHandlerTest {
    static testMethod void setSampleIdTest(){
        Match_Record__c mr = new Match_Record__c();
        List <Match_Record__c> mrList = new List <Match_Record__c>();
        
        Account acc = (Account)TestFactory.createSObject(new Account(),true);
        Contact con = (Contact)TestFactory.createSObject(new Contact(AccountId = acc.Id),true);
        TestFactory.createSObject(new Guardant_360_Sample__c(
                Name = 'name',
                Contact__c = con.Id,
                Account__c = acc.Id),true);
        
        mr.Name = 'name';
        mr.Match_ID__c = 'name';
        mr.Portal_Sample_ID__c = 'sample';
        mr.Last_Match_API_Update__c = System.now();
        
        insert mr;
        mrList.add(mr);
        
        POD__c pod = new POD__c();
        pod.Match_Record__c = mr.Id;
        insert pod;
        

        
        mr.Referred__c = true;
        mr.Permission_to_Connect_with_Pharma__c = true;
        mr.Client_Notes__c = 'client notes';
        mr.Guardant_Notes__c = 'guardant notes';
        mr.Enrollment_Status__c = 'New';
        mr.Match_Priority__c = 'High';
        mr.Match_Status__c = 'Pending';
        mr.Show_to_Customer__c = true;
        mr.Date_of_1st_Contact__c = System.now();
        mr.Date_of_Last_Contact__c = System.now();
        mr.Date_Enrolled__c = System.now();
        mr.Date_Ineligible__c = System.now();
        mr.Date_Referred__c = System.now();
        mr.Date_of_Failed_Screening__c = System.now();
        
        update mr;
        
        mr.Referred__c = false;
        mr.Permission_to_Connect_with_Pharma__c = false;
        mr.Client_Notes__c = 'client notes2';
        mr.Guardant_Notes__c = 'guardant notes2';
        mr.Enrollment_Status__c = 'Closed';
        mr.Match_Priority__c = 'Low';
        mr.Match_Status__c = 'Accepted';
        mr.Show_to_Customer__c = false;
        mr.Date_of_1st_Contact__c = System.now()+1;
        mr.Date_of_Last_Contact__c = System.now()+1;
        mr.Date_Enrolled__c = System.now()+1;
        mr.Date_Ineligible__c = System.now()+1;
        mr.Date_Referred__c = System.now()+1;
        mr.Date_of_Failed_Screening__c = System.now()+1;
        mr.Send_POD__c = true;
        mr.Custom_Signature__c = 'Rick Lanman, MD';
        mr.X1st_Paragraph__c = 'These are words for a paragraph';
        mr.Enrollment_Sub_Status__c = 'Ineligible';
        mr.Sub_Status_Reason__c = 'Death';
        
        
        update mr;
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('callout');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        
        Test.setMock(HttpCalloutMock.class, mock);

    }

}