objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/efaxapp__Sent_Fax__c.object
<CustomObject>
    <fields>
        <fullName>Guardant_360_Sample__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guardant 360 Sample #</label>
        <referenceTo>Guardant_360_Sample__c</referenceTo>
        <relationshipLabel>Sent Faxes</relationshipLabel>
        <relationshipName>Sent_Faxes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resend__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Resent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>efaxapp__Attachment_ID__c</fullName>
        <label>Attachment ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>efaxapp__Fax_Number__c</fullName>
        <label>Fax Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>efaxapp__Parent_ID__c</fullName>
        <label>Parent ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>efaxapp__Send_Date__c</fullName>
        <label>Send Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>efaxapp__Sent_Date__c</fullName>
        <label>Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>efaxapp__Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Sent Fax</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Sent Fax #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sent Faxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestResendFaxTrigger.cls
@IsTest
public class TestResendFaxTrigger {
    static testmethod void testexecute() {
        List<Account> lstAcc = Test_Data_Factory.createAccounts(1, null);
        insert lstAcc;
        List<Contact> lstContact = Test_Data_Factory.createContacts(lstAcc);
        insert lstContact;

        Guardant_360_Sample__c rep = new Guardant_360_Sample__c(
        	Name ='Test', 
        	Account__c = lstAcc[0].Id, 
        	Contact__c = lstContact[0].Id
        );
        insert rep;

        Attachment att = new Attachment(
        	ParentId = rep.Id,
        	Name = 'Test',
        	Body = Blob.valueOf('Test Attachment Body')
        );
        insert att;

        efaxapp__Sent_Fax__c fax = new efaxapp__Sent_Fax__c(
        	efaxapp__Fax_Number__c = '132456346',
         	efaxapp__Attachment_ID__c = att.Id,
         	efaxapp__Subject__c = 'Test',
         	Guardant_360_Sample__c = rep.Id,
         	efaxapp__Parent_ID__c = rep.Id,
         	efaxapp__Send_Date__c = Datetime.now().addminutes(-5),
         	efaxapp__Sent_Date__c = Datetime.now()
        );
        insert fax;

        system.debug(fax);

        Test.startTest();
        fax.Resend__c = true;
        update fax;      
        Test.stopTest();
        List<Attachment> atts = [Select Id, Name from Attachment];
        for(Attachment a : atts){
        	System.assertNotEquals(att.Id, a.Id);
        }
    }
}