objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Unqualified_by_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unqualified by CS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Assistant</fullName>
                </value>
                <value>
                    <fullName>Billing Specialist</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>CEO/COO</fullName>
                </value>
                <value>
                    <fullName>Certified Nurse Assistant</fullName>
                </value>
                <value>
                    <fullName>Clinical Trials Manager</fullName>
                </value>
                <value>
                    <fullName>Cytologist/Cytotechnologist</fullName>
                </value>
                <value>
                    <fullName>General MD</fullName>
                </value>
                <value>
                    <fullName>Genetic Counselor</fullName>
                </value>
                <value>
                    <fullName>Gynecologic Oncologist</fullName>
                </value>
                <value>
                    <fullName>Hematologist</fullName>
                </value>
                <value>
                    <fullName>Hematology/Oncology</fullName>
                </value>
                <value>
                    <fullName>Internist</fullName>
                </value>
                <value>
                    <fullName>Interventional Radiologist</fullName>
                </value>
                <value>
                    <fullName>Lab Manager</fullName>
                </value>
                <value>
                    <fullName>Lab Person</fullName>
                </value>
                <value>
                    <fullName>Medical Assistant</fullName>
                </value>
                <value>
                    <fullName>Medical Oncologist</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Nurse Navigator</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Nursing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Office Staff</fullName>
                </value>
                <value>
                    <fullName>Oncological Urologist</fullName>
                </value>
                <value>
                    <fullName>Oncology Nurse</fullName>
                </value>
                <value>
                    <fullName>Pathologist</fullName>
                </value>
                <value>
                    <fullName>Pediatric Oncologist</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Surgical Oncologist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Marketable_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketable User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NPI_Number__c</fullName>
        <inlineHelpText>Read only field used to sync with LIMS Physicians, domestic and international.</inlineHelpText>
        <label>NPI Number</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unqualified_by_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unqualified by CS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT(Account__r.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <formula>TEXT(Contact__r.Contact_Role__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Role</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NPI_Records__c.object
<CustomObject>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI_Number__c</fullName>
        <externalId>true</externalId>
        <label>NPI Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NPI Record</label>
    <nameField>
        <label>NPI Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPI Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MarketableContactBatchTest.cls
@IsTest(SeeAllData=false)
public with sharing class MarketableContactBatchTest {

    @TestSetup
    public static void setupObjects() {
        ContactActionsTest.SetupObjects();
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        c.Contact_Role__c = 'Surgical Oncologist';
        c.Email = 'test@sample.com';
        update c;
        // c.Contact_Role__c = 'Surgical Oncologist';
       // c.Email = '';
       // update c;
    }

    @IsTest
    public static void testBatch(){
    string recordtypeidval = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Commercial Account').getRecordTypeId();
        Account a1 = new Account(Account_Type__c = 'Clinical Account US',name='test',recordtypeId=recordtypeidval);
        insert a1;
        contact c= new contact();
        c.lastName ='test';
        c.Contact_Role__c = 'Surgical Oncologist';
        c.Email = '';
        c.Marketable_User__c = TRUE;
        c.accountid=a1.id;
        insert c;
        MarketableContactBatch b = new MarketableContactBatch();
        Database.executeBatch(b,50);
    }
     @IsTest
    public static void testContactService(){
    List<contact> csList = new List<contact>();
    string recordtypeidval = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Commercial Account').getRecordTypeId();
        Account a1 = new Account(Account_Type__c = 'Clinical Trial Account',name='test',recordtypeId=recordtypeidval);
        insert a1;
        NPI_Records__c  np = new NPI_Records__c(Last_Name__c='hdhhds',NPI_Number__c='122222233');
        
        insert np;
        contact c= new contact();
        c.lastName ='test';
        c.Contact_Role__c = 'Surgical Oncologist';
        c.Email = '';
        c.accountid=a1.id;
        c.Marketable_User__c = TRUE;
        c.actual_npi__c=np.id;
        insert c;
        csList.add(c);
        test.startTest();
       
       ContactService cs= new  ContactService();
       cs.markContactMarketable(csList);
       test.stoptest();
    }
     
    @IsTest
    public static void testContactServicesample(){
    List<contact> csList = new List<contact>();
    string recordtypeidval = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Commercial Account').getRecordTypeId();
        Account a1 = new Account(Account_Type__c = 'Clinical Account US',name='test',recordtypeId=recordtypeidval);
        insert a1;
        NPI_Records__c  np = new NPI_Records__c(Last_Name__c='hdhhds',NPI_Number__c='122222233');
        
        insert np;
        contact c= new contact();
        c.lastName ='test';
        c.Contact_Role__c = 'Surgical Oncologist';
        c.Email = 'test@gmail.com';
        c.accountid=a1.id;
        c.actual_npi__c=np.id;
        c.Marketable_User__c = TRUE;
        c.Unqualified_by_CS__c = true;
        insert c;
        Guardant_360_Sample__c gh=new Guardant_360_Sample__c(name='Ass900',Account__c=a1.id,Contact__c=c.id);
        insert gh;
        csList.add(c);
        test.starttest();
        ContactService cs= new  ContactService();
       cs.markContactMarketable(csList);
       test.stoptest();
       }
        
        
    @IsTest
    public static void testContactService1(){
    List<contact> csList = new List<contact>();
    string recordtypeidval = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Commercial Account').getRecordTypeId();
        Account a1 = new Account(Account_Type__c = 'Clinical Account US',name='test',recordtypeId=recordtypeidval);
        insert a1;
        NPI_Records__c  np = new NPI_Records__c(Last_Name__c='hdhhds',NPI_Number__c='122222233');
        
        insert np;
        contact c= new contact();
        c.lastName ='test';
        c.Contact_Role__c = 'Surgical Oncologist';
        c.Email = 'asdsaf@gmail.com';
        c.accountid=a1.id;
        c.actual_npi__c=np.id;
        c.Marketable_User__c = TRUE;
        insert c;
        Guardant_360_Sample__c gh=new Guardant_360_Sample__c(name='Ass900',Account__c=a1.id,Contact__c=c.id);
        insert gh;
        
        csList.add(c);
        test.startTest();
        contact con= new contact();
        con.lastName ='test';
        con.Contact_Role__c = 'Cytologist/Cytotechnologist';
        con.Email = 'asdsaf@gmail.com';
        con.accountid=a1.id;
        con.actual_npi__c=np.id;
        con.Marketable_User__c = TRUE;
        insert con;
        csList.add(con);
       ContactService cs= new  ContactService();
       cs.markContactMarketable(csList);
       ContactService.checkIfQualifiedRole(con);
       map<id,date> cMap=new map<id,Date>();
       cMap.put(con.id,Date.today());
       ContactService.updateContactEmailDate(cMap);
       test.stoptest();
    }
}