objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Account Type</description>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Recipient</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Tier 3</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 15</fullName>
                </value>
                <value>
                    <fullName>Big Pharma Top 30</fullName>
                </value>
                <value>
                    <fullName>Biotech</fullName>
                </value>
                <value>
                    <fullName>Clinical Account  International</fullName>
                </value>
                <value>
                    <fullName>Clinical Account US</fullName>
                    <default>true</default>
                    <label>Clinical Account US</label>
                </value>
                <value>
                    <fullName>Clinical Trial Account</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial Account International</fullName>
                </value>
                <value>
                    <fullName>CROs</fullName>
                </value>
                <value>
                    <fullName>Distributor International</fullName>
                </value>
                <value>
                    <fullName>Distributor US</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Patient Advocacy Group</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account International</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Account US</fullName>
                </value>
                <value>
                    <fullName>Research Account International</fullName>
                </value>
                <value>
                    <fullName>Research Account US</fullName>
                </value>
                <value>
                    <fullName>Reseller International</fullName>
                </value>
                <value>
                    <fullName>Reseller US</fullName>
                </value>
                <value>
                    <fullName>GH Headquarters</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Pharma VIP</fullName>
                </value>
                <value>
                    <fullName>Big Pharma</fullName>
                    <label>Big Biopharma</label>
                </value>
                <value>
                    <fullName>Small Pharma</fullName>
                    <label>Small Biopharma</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma Parent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <displayFormat>GHI-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Billing_Street_1__c</fullName>
        <label>Billing Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street_2__c</fullName>
        <label>Billing Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Push_to_LabVantage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to push updated account information to LIMS and ERP for previously-qualified (but no longer qualified) accounts. Otherwise, use the &apos;Qualified?&apos; checkbox</description>
        <inlineHelpText>Use this instead of &apos;Qualified?&apos; to push updated account information to LIMS for previously-qualified (but no longer qualified) accounts.</inlineHelpText>
        <label>Push to LabVantage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Qualified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualified_to_send_to_LIMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger updated field. If there is one contact qualified, Account qualified</description>
        <inlineHelpText>Trigger updated field. If there is one contact qualified, Account qualified</inlineHelpText>
        <label>Qualified to send to LIMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_to_LIMS__c</fullName>
        <description>Timestamp last SQS message sent to LIMS</description>
        <label>Sent to LIMS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Site_Number__c</fullName>
        <label>Trial Site Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AdminTriggerToggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Bypass_Account_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this to deactivate the Account Triggers</inlineHelpText>
        <label>Bypass Account Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Admin Trigger Toggle</label>
</CustomObject>

classes/AccountActionsTest.cls
@IsTest(SeeAllData=false)
public class AccountActionsTest {

    @TestSetup
    public static void SetupObjects(){
        AdminTriggerToggle__c toggle = new AdminTriggerToggle__c();
        toggle.Bypass_Account_Trigger__c = false;
        insert toggle;
        //Create Account
        TestFactory.createSObject(new Account(), true);
    }
    @IsTest
    public static void test_sendAccountsToLims() {
        List<Account> accounts = [
                SELECT
                        Id,
                        Name,
                        BillingStreet,
                        BillingCity,
                        Phone,
                        Fax,
                        Sent_to_LIMS__c,
                        Account__c,
                        BillingState,
                        BillingCountry,
                        BillingPostalCode,
                        Qualified__c,
                        AccountNumber,
                        Account_Type__c,
                        Billing_Street_1__c,
                        Billing_Street_2__c,
                        BillingLatitude,
                        BillingLongitude,
                        Qualified_to_send_to_LIMS__c,
                        Push_to_LabVantage__c, 
                        Trial_Site_Number__c  
                FROM Account];
        Test.startTest();
        AccountActions.sendAccountsToLims(accounts, 'new');
        AccountActions.sendChangesToLIMS(new Map<Id,Account>(accounts), new Map<Id,Account>(accounts));
        AccountActions.buildPayload(accounts[0],'new');
        Test.stopTest();
    }
    @IsTest
    public static void test_accountTriggerHandler() {
         Account a1 = (Account) TestFactory.createSObject(new Account(Account_Type__c = 'Clinical Account US'), true);
         delete a1;
        //delete a;
        //undelete a;
        AccountTriggerHandler handler = new AccountTriggerHandler(false,0);
        Boolean isTrigger = handler.IsTriggerContext;
        Boolean isVFPage = handler.IsVisualforcePageContext;
        Boolean isWS = handler.IsWebServiceContext;
        Boolean isAnon = handler.IsExecuteAnonymousContext;

    }
}