objects/Account.object
<CustomObject>
    <fields>
        <fullName>Push_To_TheraPak__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Push To TheraPak</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Kits_Clinical_domestic__c</fullName>
        <inlineHelpText>378556 - Guardant Health 360 Specimen Collection &amp; Shipping Kit (Domestic/Commercial)</inlineHelpText>
        <label>CLIA Calif LDT Kit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kits_Clinical_int_l__c</fullName>
        <inlineHelpText>378819 - Guardant Health 360 Specimen Collection &amp; Shipping Kit (International/Commercial)</inlineHelpText>
        <label>Kits-Clinical (int&apos;l-NOT EU)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Push_To_TheraPak__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Push To TheraPak</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_Case_Push_To_TheraPak.cls
@IsTest(SeeAllData=false)
public class Test_Case_Push_To_TheraPak {

    static testMethod void PushToTheraPak() {
        List<Account> lstAcc = Test_Data_Factory.createAccounts(10, null);
        insert lstAcc;
        
        List<Case> lstCase = Test_Data_Factory.createCases(lstAcc, '01280000000HmU6');
        
        for(Case c: lstCase) {
            c.Push_To_TheraPak__c = true;
            c.Kits_Clinical_domestic__c = 1;
            c.Kits_Clinical_int_l__c = 1;
        }
        
        insert lstCase;
    }
}