objects/Activity.object
<CustomObject>
    <fields>
        <fullName>MD_Granted_Permission_to_Connect__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, the Connected Trial Site field must be filled before the outreach activity can be saved</inlineHelpText>
        <label>MD Granted Permission to Connect?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trial_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connected Trial Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TaskService.cls
public with sharing class TaskService {

    public static void createYuzuLink(List<Task> outreachActivities) {
        for (Task task : outreachActivities) {
            if (task.Subject == 'Outreach Activity' && task.MD_Granted_Permission_to_Connect__c == true && task.Trial_Site__c != null) {
                callYuzuService(task.WhatId);
            }
        }
    }

    @Future(Callout=true)
    public static void callYuzuService(Id matchRecordId) {
        MatchRecordService service = new MatchRecordService();
        service.mRecord = MatchRecordSelector.queryMatchRecordForYuzu(matchRecordId);
        service.assignStudyPageURL();
    }

    public static void updateLastEmail(Set<Id> taskIdsInserted) {
        List<Task> emailTasksWithRelations = TaskSelector.selectEmailTasksWithRelations(taskIdsInserted);
        Map<Id, Date> contactIdEmailDate = new Map<Id, Date>();
        //System.debug('emailTasksWithRelations'+emailTasksWithRelations);
        for (Task task : emailTasksWithRelations) {
            for (TaskRelation relation : task.TaskRelations) {
                contactIdEmailDate.put(relation.RelationId, task.ActivityDate);
            }
        }
        if (contactIdEmailDate.size() > 0) {
            ContactService.updateContactEmailDate(contactIdEmailDate);
        }
    }
}