objects/AdminTriggerToggle__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Bypass_Contact_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Contact Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Admin Trigger Toggle</label>
</CustomObject>

objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Match_Key__c</fullName>
        <label>Match Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Patient ID</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Show to Customer?</label>
        <type>Checkbox</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_ID__c</fullName>
        <displayFormat>PID-{00000}</displayFormat>
        <externalId>true</externalId>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer_Match_Key_s__c</fullName>
        <description>Match records where show to customer is checked</description>
        <inlineHelpText>Match records where show to customer is checked</inlineHelpText>
        <label>Show to Customer Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer__c</fullName>
        <formula>!ISBLANK(Show_to_Customer_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show to Customer</label>
        <type>Checkbox</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PatientServiceTest.cls
@IsTest(SeeAllData=false)
public with sharing class PatientServiceTest {

    @TestSetup
    public static void setupObjects() {
        AdminTriggerToggle__c toggle = new AdminTriggerToggle__c();
        toggle.Bypass_Contact_Trigger__c = false;
        insert toggle;
        TestFactory.createSObject(new Patient__c(), true);

    }

    @IsTest
    public static void testUpdateMatchPanelFields() {
        Patient__c patient = [SELECT Id, Show_to_Customer_Match_Key_s__c FROM Patient__c LIMIT 1];
        System.assertEquals(null, patient.Show_to_Customer_Match_Key_s__c);
        TestFactory.createSObject(new Match_Record__c(
                Patient_ID__c = patient.Id,
                Show_to_Customer__c = true,
                Match_Key__c = 'test'), true);
        PatientService.updateMatchPanelFields(new Set<Id>{patient.Id});
        patient = [SELECT Id, Show_to_Customer_Match_Key_s__c FROM Patient__c LIMIT 1];
        System.assertEquals('test', patient.Show_to_Customer_Match_Key_s__c);
    }

    @IsTest
    public static void testGetLocalDateTime() {
        Datetime now = Datetime.now();
        Datetime localNow = PatientService.getLocalDateTime(now);
        System.assert(now != localNow);
    }

}