objects/Affilation__c.object
<CustomObject>
    <fields>
        <fullName>Account_Qualified__c</fullName>
        <formula>Account__r.Qualified__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Qualified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_in_LIMS__c</fullName>
        <formula>NOT(ISBLANK(Account__r.Sent_to_LIMS__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account in LIMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Affiliated_Fax__c</fullName>
        <label>Affiliated Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Affilations</relationshipLabel>
        <relationshipName>Affilations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delivery_Report_Type__c</fullName>
        <label>Delivery Report Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Courier</fullName>
                </value>
                <value>
                    <fullName>Portal and Fax</fullName>
                </value>
                <value>
                    <fullName>Fax &amp; Portal</fullName>
                    <isActive>false</isActive>
                    <label>Fax &amp; Portal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NY_Sample__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New York Sample</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Long_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs Long Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Treatment__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Needs Treatment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_NPI_No__c</fullName>
        <formula>Contact__r.NPI_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Other NPI No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physician_Billing_Type__c</fullName>
        <label>Billing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical Trial : ROW</fullName>
                </value>
                <value>
                    <fullName>Clinical Trial : US</fullName>
                </value>
                <value>
                    <fullName>DirectBill : US</fullName>
                </value>
                <value>
                    <fullName>Distributors : ROW</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Clinical Utility</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - LUNAR</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Pharma</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Proficiency</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Promotional</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - Quality Testing</fullName>
                </value>
                <value>
                    <fullName>Do Not Bill - ROW</fullName>
                </value>
                <value>
                    <fullName>Financial Indigent</fullName>
                </value>
                <value>
                    <fullName>Medicaid</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharma : ROW</fullName>
                </value>
                <value>
                    <fullName>Pharma : US</fullName>
                </value>
                <value>
                    <fullName>Private Insurance/Employee Health Plan</fullName>
                </value>
                <value>
                    <fullName>Private Insurance/Employee Health Plan No OOP</fullName>
                </value>
                <value>
                    <fullName>Research : ROW</fullName>
                </value>
                <value>
                    <fullName>Research : US</fullName>
                </value>
                <value>
                    <fullName>Self-Pay Patient</fullName>
                </value>
                <value>
                    <fullName>Self-Pay Sponsored</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_User_Name__c</fullName>
        <label>Portal User Name</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Push_to_Labvantage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Push to Labvantage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualified_AF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Qualified AF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sent_to_LIMS__c</fullName>
        <label>Sent to LIMS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Affilation</label>
    <nameField>
        <displayFormat>AF-{000000000}</displayFormat>
        <label>Affilation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affilations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ModifiedRecord__e.object
<CustomObject>
    <fields>
        <fullName>IsDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDeleted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>RecordId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>ModifiedRecord</label>
    <pluralLabel>ModifiedRecord</pluralLabel>
</CustomObject>

classes/AffiliationActions.cls
public with sharing class AffiliationActions {

    public static final string FIELDSET_NAME = 'LIMS_Affiliation_Change_Tracking';

    public static void SendChangesToLIMS(Map<ID,Affilation__c> oldRecordMap, Map<ID,Affilation__c> newRecordMap){
        List<Affilation__c> changedRecords = new List<Affilation__c>(); //list records to send
        //Based on values passed, determine if new, update or delete.
        String dmlType = '';
        if(oldRecordMap != null && newRecordMap != null)dmltype = 'update';
        //if(oldRecordMap == null && newRecordMap != null){
        //  dmltype = 'new';
  //          for(Affilation__c myNewRecord : newRecordMap.values())
        //       if(myNewRecord.Account_Qualified__c &&
  //                      (myNewRecord.Push_to_Labvantage__c || myNewRecord.Qualified_AF__c))changedRecords.add(myNewRecord);
        //}
        //if(oldRecordMap != null && newRecordMap == null){
        //  dmltype = 'delete';
        //  changedRecords.add(oldRecordMap.values());
        //}

        if(dmlType == 'update'){

            string objectLabel = string.valueOf(oldRecordMap.getSObjectType().getDescribe().getLabel());
            List<Schema.FieldSetMember> trackedFields = Lims.LookupTrackedFields(new String[]{'Affilation__c'},FIELDSET_NAME);
         
            for(ID recordID:newRecordMap.keySet()){
                Boolean trackedFieldChanged = false;
                Affilation__c myNewRecord = newRecordMap.get(recordID);
                Affilation__c myOldRecord = oldRecordMap.get(recordID);

                for (Schema.FieldSetMember fsm : trackedFields) {
                    String fieldName  = fsm.getFieldPath();
                    String fieldLabel = fsm.getLabel();
                    if (myNewRecord.get(fieldName) != myOldRecord.get(fieldName))trackedFieldChanged = true;
                }
                if(trackedFieldChanged)changedRecords.add(myNewRecord);
            }
        }
        sendQualifiedAffiliationsToLims(changedRecords,dmlType);
        //List<Id> accountsNotInLIMS = new List<Id>();

        ////Loop through changed records and add to LIMS Objects
        ////Re-query so not read only
        //changedRecords = queryAffiliation(changedRecords);
        //for(Affilation__c a : changedRecords){
        //    System.debug('===Affiliation: '+a);
        //    String jsonPayload = BuildPayload(a, dmltype);
        //    Lims.sendToLIMS(jsonPayload);
        //    a.Sent_to_LIMS__c = String.valueOf(datetime.now()); //Timestamp Affiliation with system time of SMS sending
        //}
        ////if(dmltype == 'new') 
        //update changedRecords;
    }

    public static void sendQualifiedAffiliationsToLims(List<Affilation__c> affiliationRecords, String dmlType){
      List<Affilation__c> qualifiedAffiliations = new List<Affilation__c>();
      for(Affilation__c a : affiliationRecords){
        if(a.Account_Qualified__c &&
            (a.Push_to_Labvantage__c || a.Qualified_AF__c))qualifiedAffiliations.add(a);
      }
      sendAffiliationsToLims(qualifiedAffiliations,dmltype);
    }

    public static void sendAffiliationsToLims(List<Affilation__c> affiliationRecords, String dmlType){
      List<Affilation__c> affiliationsToUpdate = new List<Affilation__c>();
      for(Affilation__c a : affiliationRecords){
            System.debug('===Affiliation: '+a);
            String jsonPayload = BuildPayload(a, dmlType);
            Lims.sendToLIMS(jsonPayload);
            //if(dmlType == 'new'){
              affiliationsToUpdate.add(new Affilation__c(Id = a.Id, Sent_to_LIMS__c = String.valueOf(datetime.now())));
            //}else{
            //  a.Sent_to_LIMS__c = String.valueOf(datetime.now()); //Timestamp Accounts with system time of SMS sending
            //}
            
        }
        if(affiliationsToUpdate.size() != 0 && !System.isQueueable() && Limits.getQueueableJobs() == 0){
          System.enqueueJob(new QUEUEABLE_AffilationUpdate(affiliationsToUpdate));
        }
    }

    public static string BuildPayload(Affilation__c a, String type){
        Lims.Affiliation aff = new Lims.Affiliation();
        aff.Object_id = 'Affiliation';
        aff.Status = type;
        aff.details.AccountLinked = String.valueOf(!a.Account_in_LIMS__c);  //Boolean
        aff.details.affiliation_id = a.Id;                                  //String(18)
        aff.details.contact_id = a.Contact__c;                              //String(18)
        aff.details.account_id = a.Account__c;                              //String(18)    
        aff.details.user_name = a.Portal_User_Name__c;                      //String(80)
        aff.details.report_delivery_method = a.Delivery_Report_Type__c;     //String(255)
        aff.details.needs_treatment = String.valueOf(a.Needs_Treatment__c); //Boolean
        aff.details.is_newyork_physician = String.valueOf(a.NY_Sample__c);  //Boolean
        aff.details.billing_indicator = a.Physician_Billing_Type__c;        //String(255)
        aff.details.fax = a.Affiliated_Fax__c;                              //String(40)
        aff.details.other_npino = a.Other_NPI_No__c;
        aff.details.is_qualified = String.valueOf(a.Qualified_AF__c);
        aff.details.push_to_labvantage = String.valueOf(a.Push_to_Labvantage__c);
        aff.details.report_additional_information = String.valueOf(a.Needs_Long_Report__c);
        return JSON.serialize(aff);
    }
    
     public static void createPlatformEvent(List<Affilation__c> affRecords, String dmlType){
       
        List<ModifiedRecord__e> publishEvents = new List<ModifiedRecord__e>();
        for(Affilation__c a : affRecords){
            ModifiedRecord__e    eve = new ModifiedRecord__e();
            eve.ObjectName__c = 'Affilation__c' ; 
            eve.recordid__C= a.id ; 
            if(dmlType == 'Delete'){
            eve.IsDeleted__c =true;
            }
            else{
             eve.IsDeleted__c =false;

            }
            
            publishEvents.add(eve);            
        }
        if(publishEvents.size()>0){
            EventBus.publish(publishEvents);
        }
    }

}