objects/Case.object
<CustomObject>
    <fields>
        <fullName>Accession_No__c</fullName>
        <label>Accession Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CANCEL</fullName>
                </value>
                <value>
                    <fullName>TAT ALERT</fullName>
                </value>
                <value>
                    <fullName>AMEND</fullName>
                </value>
                <value>
                    <fullName>CORRECTED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Guardant_360_Sample__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accession #</label>
        <referenceTo>Guardant_360_Sample__c</referenceTo>
        <relationshipLabel>Cases (Guardant 360 Sample)</relationshipLabel>
        <relationshipName>Cases_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initiated__c</fullName>
        <label>Initiated</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Action__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CANCEL-External</fullName>
                </value>
                <value>
                    <fullName>CANCEL-Internal</fullName>
                </value>
                <value>
                    <fullName>TAT ALERT-External</fullName>
                </value>
                <value>
                    <fullName>TAT ALERT-Internal</fullName>
                </value>
                <value>
                    <fullName>AMEND-External</fullName>
                </value>
                <value>
                    <fullName>AMEND-Internal</fullName>
                </value>
                <value>
                    <fullName>CORRECTED-External</fullName>
                </value>
                <value>
                    <fullName>CORRECTED-Internal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technical_Reason__c</fullName>
        <label>Technical Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Technical_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
                <value>
                    <fullName>Alternative Treatment</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Lab issue</fullName>
                </value>
                <value>
                    <fullName>Missing Identifier</fullName>
                </value>
                <value>
                    <fullName>Missing Signature</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Couldn&apos;t Qualify</fullName>
                </value>
                <value>
                    <fullName>Broken/Leaked</fullName>
                </value>
                <value>
                    <fullName>Expired Tube</fullName>
                </value>
                <value>
                    <fullName>Compromised</fullName>
                </value>
                <value>
                    <fullName>Identifier</fullName>
                </value>
                <value>
                    <fullName>QNS</fullName>
                </value>
                <value>
                    <fullName>Wrong Tube</fullName>
                </value>
                <value>
                    <fullName>Dr. Hold</fullName>
                </value>
                <value>
                    <fullName>Case Resolution Delayed</fullName>
                </value>
                <value>
                    <fullName>Qualification Delayed</fullName>
                </value>
                <value>
                    <fullName>Patient Demo</fullName>
                </value>
                <value>
                    <fullName>Physician Demo</fullName>
                </value>
                <value>
                    <fullName>Results related</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>LONG TAIL</fullName>
                </value>
                <value>
                    <fullName>UVP</fullName>
                </value>
                <value>
                    <fullName>Stage I/II</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technical_Type__c</fullName>
        <label>Technical Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Initiated__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Client Request</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>TRF</fullName>
                </value>
                <value>
                    <fullName>Specimen</fullName>
                </value>
                <value>
                    <fullName>TAT ALERT</fullName>
                </value>
                <value>
                    <fullName>AMEND</fullName>
                </value>
                <value>
                    <fullName>CORRECTED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Technical_Case</fullName>
        <active>true</active>
        <businessProcess>Standard Support Process</businessProcess>
        <description>Use for Technical Cases</description>
        <label>Technical Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Guardant Samples (Account)</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DelayedCaseController.cls
/*

*@author Siva

*@date 2/27/2020 

*@description DelayedCaseController

*@History

  Author  - Date - Description
  Devendra - 05/01/2020 - ENT-16312 : Modify 'Create Delayed Case' button so that due date doesn't autopopulate
*/

public class DelayedCaseController {

    // Constructor - this only really matters if the autoRun function doesn't work right
    private final Guardant_360_Sample__c o;
    public DelayedCaseController(ApexPages.StandardController stdController) {
        this.o = (Guardant_360_Sample__c) stdController.getRecord();
    }

    // Code we will invoke on page load.
    public PageReference autoRun() {
        case cs;
        Guardant_360_Sample__c gSample;
        String theId = ApexPages.currentPage().getParameters().get('id');
    
        if(theId == null){
            return null;
        }
        List <case> csList = [select id from case where Guardant_360_Sample__c =: theId and subject = 'Delayed Sample'];
        system.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@' + csList.size());
        if(csList.size() == 0){
            Id technicalCaseRTId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Technical_Case').getRecordTypeId();
    
            for (Guardant_360_Sample__c gs: [select id, name, account__c, contact__c from Guardant_360_Sample__c where id =: theId]) {
            cs = new
            case (BusinessHoursid = label.businesshour, Accession_No__c = gs.name, accountid = gs.account__c, Action__c = 'TAT ALERT', ContactID = gs.contact__c,
             Guardant_360_Sample__c = gs.id, Initiated__c = 'TAT ALERT-Internal', Origin = 'Internal', ownerid = '00G80000002vLPH', Priority = 'Medium', recordtypeid = technicalCaseRTId, Status = 'New',
             Subject = 'Delayed Sample', Technical_Reason__c = 'Lab Issue', Technical_Type__c = 'TAT ALERT');
            }
            insert cs;
            DelayedCaseCheckbox.updatingSample(theId);
            
            // Redirect the user back to the original page
            PageReference pageRef = new PageReference('/' + cs.id);
            pageRef.setRedirect(true);
            return pageRef;
        }else{
            PageReference pageRef = new PageReference('/' + theID);
            pageRef.setRedirect(true);
            return pageRef;
        }
    }
}