objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sample__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Sample</label>
        <referenceTo>Guardant_360_Sample__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guardant 360 Samples</relationshipLabel>
        <relationshipName>Guardant_360_Samples</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QUEUEABLE_ContactLastSampleDate.cls
public with sharing class QUEUEABLE_ContactLastSampleDate implements Queueable {
    public Set<Id> contactIds = new Set<Id>();

    public QUEUEABLE_ContactLastSampleDate(Set<Id> contactIds) {
        this.contactIds = contactIds;
    }

    public void execute(QueueableContext context) {
        List<Contact> contactList = [
                SELECT Id, Actual_NPI__c, (
                        SELECT Id, Date_Received__c
                        FROM Guardant_360_Samples__r
                        ORDER BY Date_Received__c DESC
                        LIMIT 1
                )
                FROM Contact
                WHERE Id IN :contactIds
        ];
        Set<Id> npiIds = new Set<Id>();
        for (Contact c : contactList) {
            c.Last_Sample__c = c.Guardant_360_Samples__r[0].Id;
            if (c.Actual_NPI__c != null) {
                npiIds.add(c.Actual_NPI__c);
            }
        }
        update contactList;
        //send NPI set to Method
        //System.debug('===npiIds: ' + npiIds);
        if(npiIds.size()>0){
            NpiService.updateTotalSamples(npiIds);
        }



    }

}