objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Contact__c</fullName>
        <displayFormat>GHC-{000000000}</displayFormat>
        <externalId>true</externalId>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Connected_Trial_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to trial sites from the same trial.</inlineHelpText>
        <label>Connected Trial Site</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a trial site for this trial.</errorMessage>
            <filterItems>
                <field>$Source.Trial_Name__c</field>
                <operation>equals</operation>
                <valueField>Study_Site__c.Study__r.Id</valueField>
            </filterItems>
            <infoMessage>Use the Search String &apos;*TS-*&apos; to show all trial sites for this match&apos;s trial</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Match Records Connected to this Trial Site</relationshipLabel>
        <relationshipName>Match_Records1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Match_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PTC_Connection_Preference__c</fullName>
        <description>Mirrors same field in Connected Trial Site</description>
        <formula>TEXT(Connected_Trial_Site__r.PTC_Connection_Preference__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PTC Connection Preference</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pharma_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pharma Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Studies_Sites_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trial Site Contacts</relationshipLabel>
        <relationshipName>Studies_Sites_Contacts_del</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Copied from the Trial Site Contact&apos;s contact record, but can be edited.</inlineHelpText>
        <label>Email</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTC_Connection_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This opts the contact into receiving PTC Emails from Yuzu.</inlineHelpText>
        <label>PTC Connection Opt-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Study_Sites__c</fullName>
        <label>Trial Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Trial Site Contacts</relationshipLabel>
        <relationshipName>Studies_Sites_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Trial Site Contact</label>
    <nameField>
        <label>Trial Site Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Site Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>Pharma_Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pharma Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trials</relationshipLabel>
        <relationshipName>Studies1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTC_Connection_Preference__c</fullName>
        <description>NS:06/13/18</description>
        <label>PTC Connection Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Connect to Pharma</fullName>
                </value>
                <value>
                    <fullName>Connect to Trial Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pharma_Company__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp;Study__r.Pharma_Company__r.Id, Study__r.Pharma_Company__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pharma Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <label>Trial</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipLabel>Trial Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Trial Site</label>
    <nameField>
        <label>Trial Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trial Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MatchRecordServiceTest.cls
@IsTest(SeeAllData=false)
private with sharing class MatchRecordServiceTest {

    @TestSetup
    private static void SetupObjects() {
        TestFactory.createSObject(new Match_Record__c(Match_ID__c = 'M0001'), true);
    }

    @IsTest
    private static void beginsWithVowelTrueTest() {
        System.assertEquals(true, MatchRecordService.beginsWithVowel('Apple'));
    }

    @IsTest
    private static void beginsWithVowelFalseTest() {
        System.assertEquals(false, MatchRecordService.beginsWithVowel('Bannana'));
    }

    @IsTest
    private static void yuzuExceptionPath() {
        Match_Record__c match = [SELECT Id, Match_ID__c FROM Match_Record__c LIMIT 1];
        MatchRecordService service = new MatchRecordService();
        service.mRecord = MatchRecordSelector.queryMatchRecordForYuzu(match.Id);
        try {
            service.assignStudyPageURL();
        } catch (YuzuException e) {
            System.assertEquals('Yuzu Exception: There must be at least one Principal Investigator', e.getMessage());
        }
    }

    @IsTest
    private static void yuzuSuccessPath() {
        /*
        Match_Record__c match = [SELECT Id, Match_ID__c FROM Match_Record__c LIMIT 1];
        //Update match record to meet all minimum criteria
        Account acc = (Account) TestFactory.createSObject(new Account(), true);
        Study__c study = (Study__c) TestFactory.createSObject(new Study__c(Pharma_Company__c = acc.Id), true);
        //Add Trial Site
        Study_Site__c connectedTrialSite = (Study_Site__c) TestFactory.createSObject(
                new Study_Site__c(
                        Account_Name__c = 'Test',
                        Study__c = study.Id,
                        PTC_Connection_Preference__c = 'Connect to Trial Site'), true);
        match.Connected_Trial_Site__c = connectedTrialSite.Id;
        update match;
        //Add Trial Site Contact

        Contact con = (Contact) TestFactory.createSObject(new Contact(AccountId = acc.Id), true);
        Studies_Sites_Contact__c trialSiteContact = (Studies_Sites_Contact__c) TestFactory.createSObject(
                new Studies_Sites_Contact__c(
                        Study_Sites__c = connectedTrialSite.Id,
                        Contact__c = con.Id,
                        PTC_Connection_Opt_In__c = true,
                        Email__c = 'test@example.com'
                        ), true);

        MatchRecordService service = new MatchRecordService();
        service.mRecord = MatchRecordSelector.queryMatchRecordForYuzu(match.Id);
        service.assignStudyPageURL();

        //assert the is a link under match record
        */
    }


}