objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Fire_Match_Count_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fire Match Count Flow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Ordering_Physician_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Looks up to Contact</inlineHelpText>
        <label>Ordering Physician Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Match Records (Ordering Physician Name)</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MatchCountFlow.cls
public class MatchCountFlow {
    public static void callFlow(List<Match_Record__c> mrList){
        Set<Id> contactIds = new Set<Id>();
        for(Match_Record__c mr : mrList){
            contactIds.add(mr.Ordering_Physician_Name__c);
        }
        List <Contact> contactsToUpdate = new List <Contact>([SELECT Id, Name
                                                        FROM Contact
                                                       WHERE Id = :contactIds]);
        for(Contact c : contactsToUpdate){
            c.Fire_Match_Count_Flow__c = TRUE;
        }
        update contactsToUpdate;
    }
}