objects/Contact.object
<CustomObject
     >
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT (Account.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_NPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The NPI associated with this practitioner- regardless of how many contact records are associated.</inlineHelpText>
        <label>Actual NPI</label>
        <referenceTo>NPI_Records__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>NPI_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Assistant</fullName>
                </value>
                <value>
                    <fullName>Billing Specialist</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                </value>
                <value>
                    <fullName>CEO/COO</fullName>
                </value>
                <value>
                    <fullName>Certified Nurse Assistant</fullName>
                </value>
                <value>
                    <fullName>Clinical Trials Manager</fullName>
                </value>
                <value>
                    <fullName>Cytologist/Cytotechnologist</fullName>
                </value>
                <value>
                    <fullName>General MD</fullName>
                </value>
                <value>
                    <fullName>Genetic Counselor</fullName>
                </value>
                <value>
                    <fullName>Gynecologic Oncologist</fullName>
                </value>
                <value>
                    <fullName>Hematologist</fullName>
                </value>
                <value>
                    <fullName>Hematology/Oncology</fullName>
                </value>
                <value>
                    <fullName>Internist</fullName>
                </value>
                <value>
                    <fullName>Interventional Radiologist</fullName>
                </value>
                <value>
                    <fullName>Lab Manager</fullName>
                </value>
                <value>
                    <fullName>Lab Person</fullName>
                </value>
                <value>
                    <fullName>Medical Assistant</fullName>
                </value>
                <value>
                    <fullName>Medical Oncologist</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Nurse Navigator</fullName>
                </value>
                <value>
                    <fullName>Nurse Practitioner</fullName>
                </value>
                <value>
                    <fullName>Nursing Manager</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Office Staff</fullName>
                </value>
                <value>
                    <fullName>Oncological Urologist</fullName>
                </value>
                <value>
                    <fullName>Oncology Nurse</fullName>
                </value>
                <value>
                    <fullName>Pathologist</fullName>
                </value>
                <value>
                    <fullName>Pediatric Oncologist</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketable_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketable User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Samples__c</fullName>
        <label>Number of Samples</label>
        <summaryForeignKey>Guardant_360_Sample__c.Contact__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unqualified_by_CS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unqualified by CS</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MarketableContactBatch.cls
public class MarketableContactBatch implements Database.Batchable<SObject>{
    Set<String> marketableContactRoles = ContactService.MARKETABLE_CONTACT_ROLES;
    private String query = 'SELECT Id, Number_of_Samples__c, Account_Type__c,Unqualified_by_CS__c, Contact_Role__c, Email, Marketable_User__c ' +
            'FROM Contact WHERE (Email != null AND Contact_Role__c IN :marketableContactRoles) ' +
            'OR Marketable_User__c = TRUE '+
            'ORDER BY Actual_NPI__c ASC, Email ASC';

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope){
        ContactService service = new ContactService();
        service.markContactMarketable(scope);
    }
    public void finish(Database.BatchableContext bc){

    }
}