objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>Final_Report_Date__c</fullName>
        <label>Final Report Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Name__c</fullName>
        <inlineHelpText>Name of trial, if sample is associated with one</inlineHelpText>
        <label>Trial Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Last_Contact__c</fullName>
        <label>Date of Last Contact</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Guardant Outreach</fullName>
                </value>
                <value>
                    <fullName>Pharma Outreach</fullName>
                    <label>Pharma/Site Outreach</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                    <label>Enrolled/Prescribed</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enrollment_Sub_Status__c</fullName>
        <label>Referral Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Enrollment_Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Pharma</fullName>
                </value>
                <value>
                    <fullName>Accepted by Pharma</fullName>
                </value>
                <value>
                    <fullName>Emailed</fullName>
                </value>
                <value>
                    <fullName>Ready For Outreach</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Left Message</fullName>
                </value>
                <value>
                    <fullName>Future Consideration</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Via Match Program</fullName>
                </value>
                <value>
                    <fullName>Patient Lost to Follow Up</fullName>
                </value>
                <value>
                    <fullName>Provider Refusal</fullName>
                </value>
                <value>
                    <fullName>Patient Refusal</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Trial Change</fullName>
                </value>
                <value>
                    <fullName>Rejected by Pharma</fullName>
                </value>
                <value>
                    <fullName>Newer Test Results Available</fullName>
                </value>
                <value>
                    <fullName>Exhausted Follow-Up</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pending GH Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Report_Date__c</fullName>
        <formula>Sample_ID__r.Final_Report_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Final Report Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Reminder__c</fullName>
        <label>Follow-Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Patient_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Patient ID</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_Report__c</fullName>
        <formula>HYPERLINK(&quot;https://portal.guardanthealth.com/download_report/admin_download?request_id=&quot; &amp; Sample_ID__r.Name ,&quot;Download Patient Report&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Patient Report</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sample_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Sample ID</label>
        <referenceTo>Guardant_360_Sample__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study__c.object
<CustomObject>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MatchExtension.cls
public class MatchExtension
    {
    // Get,Set current match record info
    public Match_Record__c mr {get;set;}
    // find related match records on the sample
    public List <Match_Record__c> matchList
    {
        get
        {
            if (matchList == null)
            {
                matchList = [SELECT Enrollment_Status__c,
                                    Id,
                                    Follow_Up_Reminder__c,
                                    Name,
                                    Patient_Report__c,
                                    Final_Report_Date__c,
                                    Date_of_Last_Contact__c,
                                    Enrollment_Sub_Status__c,
                                    Sample_ID__c,
                                    Sample_ID__r.Name,                          
                                    Patient_ID__c,
                                    Trial_Name__c,
                                    Trial_Name__r.Name,
                                    Owner.Name,
                                    OwnerId
                              FROM  Match_Record__c
                             WHERE  Patient_ID__c = :mr.Patient_ID__c
                          ORDER BY  Sample_ID__r.Name DESC];
            }
            return matchList;
        }
        private set;
    }
    // set standard controller for the object
    public MatchExtension(ApexPages.StandardController stdController) {
        this.mr = (Match_Record__c)stdController.getRecord();
    }
        public static void restMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        }
}