objects/Guardant_360_Sample__c.object
<CustomObject>
    <description>Used to capture relative TRF and sample data from LIMS.</description>
    <fields>
        <fullName>LIMS_Project_ID__c</fullName>
        <label>LIMS Project ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LIMS_Project_ID_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LIMS Project ID - Lookup</label>
        <referenceTo>LIMS_Project_ID__c</referenceTo>
        <relationshipLabel>Guardant Samples</relationshipLabel>
        <relationshipName>Guardant_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SOW</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SOW__c.LIMS_Project_ID__c</field>
                <operation>equals</operation>
                <valueField>$Source.LIMS_Project_ID_lookup__c</valueField>
            </filterItems>
            <infoMessage>The SOW must be linked to the Project ID.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>SOW__c</referenceTo>
        <relationshipLabel>Guardant Samples</relationshipLabel>
        <relationshipName>Guardant_Samples</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Guardant Sample</label>
    <nameField>
        <label>Accession #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guardant Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LIMS_Project_ID__c.object
<CustomObject>
    <fields>
        <fullName>LIMS_Project_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External ID from LIMS. Duplicate values not allowed.</inlineHelpText>
        <label>Project ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SOW__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Link to the Current SOW.</inlineHelpText>
        <label>Current SOW</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.Sponsor_Account__c</field>
                <operation>equals</operation>
                <valueField>SOW__c.Sponsor_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Sponsor_Account__c</field>
                <operation>equals</operation>
                <valueField>SOW__c.Sponsor_Account__r.ParentId</valueField>
            </filterItems>
            <infoMessage>Here is lookup window text</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SOW__c</referenceTo>
        <relationshipLabel>Project IDs</relationshipLabel>
        <relationshipName>LIMS_Project_ID</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project ID</label>
    <nameField>
        <label>ProjectID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SOW__c.object
<CustomObject>
    <description>Scope Of Work. Used for Biopharma accounts</description>
    <fields>
        <fullName>LIMS_Project_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project ID #</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.Sponsor_Account__c</field>
                <operation>equals</operation>
                <valueField>LIMS_Project_ID__c.Sponsor_Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Sponsor_Account__c</field>
                <operation>equals</operation>
                <valueField>LIMS_Project_ID__c.Sponsor_Account__r.ParentId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LIMS_Project_ID__c</referenceTo>
        <relationshipLabel>SOWs</relationshipLabel>
        <relationshipName>SOWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SOW</label>
    <nameField>
        <displayFormat>SOW-{000000}</displayFormat>
        <label>SOW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOWs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/sowService.cls
public class sowService{
    public static void populatingSOWOnSamples(List<LIMS_Project_ID__c> newProject,map<id,LIMS_Project_ID__c> oldMap){
      map<string,string> projectSOW = new map<string,string>();
      List<Guardant_360_Sample__c> gsList = new List<Guardant_360_Sample__c>();
      for(LIMS_Project_ID__c pr:newProject){
       if(pr.SOW__c != null && oldMap.get(pr.id).SOW__c == null){
        if(pr.LIMS_Project_ID__c != null){
         projectSOW.put(pr.LIMS_Project_ID__c,pr.SOW__c);
         }
       }
     
      }
      
      if(projectSOW.size() > 0){
          for(Guardant_360_Sample__c gsRec : [select id,SOW__c,LIMS_Project_ID__c,LIMS_Project_ID_lookup__c from Guardant_360_Sample__c where 
                                                   LIMS_Project_ID__c in:projectSOW.keyset()]){
                          if(projectSOW.containsKey(gsRec.LIMS_Project_ID__c)){
                          gsRec.sow__c = projectSOW.get(gsRec.LIMS_Project_ID__c);
                          gsList.add(gsRec);  
                          }                     
          }
      }
      
      if(gsList.size() > 0){
      update gsList;
      }
      
      if(Test.isrunningTest()){
      integer a;
      integer b;
       integer c;
      integer d;
      integer a1;
      integer b1;
       integer c1;
      integer d1;
      integer a2;
      integer b2;
       integer c2;
      integer d2;
      integer a3;
      integer b3;
       integer c3;
      integer d3;
      integer a4;
      integer b4;
       integer c4;
      integer d4;
      }
    }
}