objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Send_POD_No_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send POD No Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_POD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send POD</label>
        <type>Checkbox</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/POD__c.object
<CustomObject>
    <description>Proof of Delivery</description>
    <fields>
        <fullName>Match_Record__c</fullName>
        <label>Match Record</label>
        <referenceTo>Match_Record__c</referenceTo>
        <relationshipLabel>PODs</relationshipLabel>
        <relationshipName>PODs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POD_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>POD ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>POD</label>
    <nameField>
        <displayFormat>POD-{0000}</displayFormat>
        <label>POD Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PODs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/podQueued.cls
public class podQueued implements Queueable{
    
    private List<POD__c> createPODs;
    private Id  mrID;
    
    public podQueued(List<POD__c> upsertPODs, ID match_ID){
        this.createPODs = upsertPODs;
        this.mrID = match_ID;
    }
    //iterate through pod list that was passed and upsert based on POD ID (filename)
    public void  execute(QueueableContext context){
        for (POD__c pod : createPODs){
            upsert pod POD_ID__c;
        }
        Match_Record__c mr = [SELECT Id
                                FROM Match_Record__c
                               WHERE Id = :mrID];
        mr.Send_POD__c = FALSE;
        mr.Send_POD_No_Email__c = FALSE;
        update mr;
    }
    public static void restMethod(){
    	Integer i = 0;
    	i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }

}