objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Achieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reached Provider?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CTA Contact Attempted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Contact_Achieved__c</fullName>
        <label>Date Reached Provider</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Contact_Attempted__c</fullName>
        <label>Date CTA Contact Attempted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Enrolled__c</fullName>
        <label>Date Enrolled/Prescribed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Last_Ditch_Email_Sent__c</fullName>
        <label>Date Last Ditch Email Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Outreach_Email_Read__c</fullName>
        <label>Date Outreach Email Read</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Outreach_Email_Sent__c</fullName>
        <label>Date Outreach Email Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_PTC_Alert_Sent__c</fullName>
        <label>Date PTC Alert Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Pharma_Permission_to_Connect__c</fullName>
        <label>Date Pharma Permission to Connect</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Referred__c</fullName>
        <label>Date Informed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Replied_to_Last_Ditch_Email__c</fullName>
        <label>Date Replied to Last Ditch Email</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Replied_to_Outreach_Email__c</fullName>
        <label>Date Replied to Outreach Email</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Screened__c</fullName>
        <label>Date Screened</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Show_to_Pharma__c</fullName>
        <label>Date Show to Customer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrolled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrolled/Prescribed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Ditch_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Last Ditch Email Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Match_Key__c</fullName>
        <label>Match Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Outreach Email Read?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Outreach Email Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Patient ID</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permission_to_Connect_with_Pharma__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Permission to Connect with Pharma?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pharma_PTC_Alert_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pharma PTC Alert Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referred__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, a referral letter will be sent to MD</inlineHelpText>
        <label>Informed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replied_to_Last_Ditch_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ENT-4687</description>
        <label>Replied to Last Ditch Email?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replied_to_Outreach_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replied to Outreach Email?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Screened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ENT-4688</description>
        <label>Screened?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Show to Customer?</label>
        <type>Checkbox</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>!ISBLANK(Closed_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enrolled__c</fullName>
        <formula>!ISBLANK(Enrolled_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enrolled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Ditch_Email_Sent__c</fullName>
        <formula>!ISBLANK(Last_Ditch_Email_Sent_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Ditch Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Read__c</fullName>
        <formula>!ISBLANK(Outreach_Email_Read_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outreach Email Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Sent__c</fullName>
        <formula>!ISBLANK(Outreach_Email_Sent_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outreach Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permission_to_Connect_with_Pharma__c</fullName>
        <formula>!ISBLANK(Perm_to_Conn_With_Pharma_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Permission to Connect with Pharma</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replied_to_Last_Ditch_Email__c</fullName>
        <formula>!ISBLANK(Replied_to_Last_Ditch_Email_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Replied to Last Ditch Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replied_to_Outreach_Email__c</fullName>
        <formula>!ISBLANK(Replied_to_Outreach_Email_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Replied to Outreach Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Screened__c</fullName>
        <formula>!ISBLANK(Screened_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Screened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer__c</fullName>
        <formula>!ISBLANK(Show_to_Customer_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show to Customer</label>
        <type>Checkbox</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PatientSelector.cls
public with sharing class PatientSelector {

    public static List<Patient__c> matchRecordsByPatient(Set<Id> patientIds) {
        return [
                SELECT Id, (
                        SELECT Id,
                                Match_Key__c,
                                Show_to_Customer__c,
                                Outreach_Email_Sent__c,
                                Outreach_Email_Read__c,
                                Replied_to_Outreach_Email__c,
                                Contact_Attempted__c,
                                Last_Ditch_Email_Sent__c,
                                Replied_to_Last_Ditch_Email__c,
                                Contact_Achieved__c,
                                Referred__c,
                                Permission_to_Connect_with_Pharma__c,
                                Pharma_PTC_Alert_Sent__c,
                                Screened__c,
                                Enrolled__c,
                                Closed__c,
                                Date_Show_to_Pharma__c,
                                Date_Outreach_Email_Sent__c,
                                Date_Outreach_Email_Read__c,
                                Date_Replied_to_Outreach_Email__c,
                                Date_Contact_Attempted__c,
                                Date_Last_Ditch_Email_Sent__c,
                                Date_Replied_to_Last_Ditch_Email__c,
                                Date_Contact_Achieved__c,
                                Date_Referred__c,
                                Date_Pharma_Permission_to_Connect__c,
                                Date_PTC_Alert_Sent__c,
                                Date_Screened__c,
                                Date_Enrolled__c,
                                Date_Closed__c
                        FROM Match_Records__r
                        WHERE IsDeleted = FALSE
                        ORDER BY Match_Key__c ASC
                )
                FROM Patient__c
                WHERE Id IN :patientIds
        ];
    }
}