objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Match_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ordering_Physician_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Looks up to Contact</inlineHelpText>
        <label>Ordering Physician Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Match Records (Ordering Physician Name)</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MatchRecordTriggerTest.cls
@IsTest
private class MatchRecordTriggerTest {
    static testMethod void makeMR() {

        Account acc = (Account) TestFactory.createSObject(new Account(), true);
        Contact con = (Contact) TestFactory.createSObject(new Contact(AccountId = acc.Id), true);
        Match_Record__c mr = (Match_Record__c) TestFactory.createSObject(new Match_Record__c(
                Name = '1',
                Match_ID__c = '1',
                Ordering_Physician_Name__c = con.Id), true);

        update mr;
        delete mr;
    }

}