objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Match_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/REST_MatchRecordBulkUpdateTest.cls
@IsTest
private class REST_MatchRecordBulkUpdateTest {
    private static String testJSON = '{'+
            '   \"records\":['+
            '       {'+
            '       \"match_id\":\"M0001\",'+
            '       \"closest_trial_site\":\"123456dfd\"'+
            '       },'+
            '       {'+
            '       \"match_id\":\"M0002\",'+
            '       \"closest_trial_site\":\"123456dfd\"'+
            '       }'+
            '   ]'+
            '}';

    @TestSetup
    static void setup(){
        //Create Trial Site

        //Create Match Record
        TestFactory.createSObject(new Match_Record__c(Match_ID__c = 'M0001'),true);
    }

    @IsTest
    static void testDecodeMatchRecords() {
        Map<String, MRecord> results = REST_MatchRecordBulkUpdate.decodeMatchRecords(testJSON);
        System.assertEquals(2,results.size());
    }

    @IsTest
    static void testBulkUpdateMR(){
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/mrBulkUpdate';
        req.httpMethod = 'PATCH';
        req.requestBody = Blob.valueOf(testJSON);

        RestContext.request = req;
        REST_MatchRecordBulkUpdate.bulkUpdateMR();
    }

    
}