objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Achieved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reached Provider?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CTA Contact Attempted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Contact_Achieved__c</fullName>
        <label>Date Reached Provider</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Contact_Attempted__c</fullName>
        <label>Date CTA Contact Attempted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Enrolled__c</fullName>
        <label>Date Enrolled/Prescribed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Last_Ditch_Email_Sent__c</fullName>
        <label>Date Last Ditch Email Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Outreach_Email_Read__c</fullName>
        <label>Date Outreach Email Read</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Outreach_Email_Sent__c</fullName>
        <label>Date Outreach Email Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_PTC_Alert_Sent__c</fullName>
        <label>Date PTC Alert Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Pharma_Permission_to_Connect__c</fullName>
        <label>Date Pharma Permission to Connect</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Referred__c</fullName>
        <label>Date Informed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Replied_to_Last_Ditch_Email__c</fullName>
        <label>Date Replied to Last Ditch Email</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Replied_to_Outreach_Email__c</fullName>
        <label>Date Replied to Outreach Email</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Screened__c</fullName>
        <label>Date Screened</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Show_to_Pharma__c</fullName>
        <label>Date Show to Customer</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrolled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrolled/Prescribed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Ditch_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Last Ditch Email Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Read__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Outreach Email Read?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Outreach Email Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Patient ID</label>
        <referenceTo>Patient__c</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permission_to_Connect_with_Pharma__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Permission to Connect with Pharma?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pharma_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pharma Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Match Records</relationshipLabel>
        <relationshipName>Match_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pharma_PTC_Alert_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pharma PTC Alert Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referred__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, a referral letter will be sent to MD</inlineHelpText>
        <label>Informed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replied_to_Last_Ditch_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ENT-4687</description>
        <label>Replied to Last Ditch Email?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replied_to_Outreach_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replied to Outreach Email?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Screened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ENT-4688</description>
        <label>Screened?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Show to Customer?</label>
        <type>Checkbox</type>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>CTA_Contact_Attempted_Match_Key_s__c</fullName>
        <description>Match records where CTA Contact Attempted is checked</description>
        <inlineHelpText>Match records where CTA Contact Attempted is checked</inlineHelpText>
        <label>CTA Contact Attempted Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTA_Contacted_Attempted_Date__c</fullName>
        <label>CTA Contacted Attempted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Closed_Match_Key_s__c</fullName>
        <description>Match records where Closed is checked</description>
        <inlineHelpText>Match records where Closed is checked</inlineHelpText>
        <label>Closed Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>!ISBLANK(Closed_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enrolled_Match_Key_s__c</fullName>
        <description>Match records where Enrolled is checked</description>
        <inlineHelpText>Match records where Enrolled is checked</inlineHelpText>
        <label>Enrolled Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrolled__c</fullName>
        <formula>!ISBLANK(Enrolled_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enrolled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Informed_Match_Key_s__c</fullName>
        <description>Match records where Informed is checked</description>
        <inlineHelpText>Match records where Informed is checked</inlineHelpText>
        <label>Informed Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Ditch_Email_Sent_Date__c</fullName>
        <label>Last Ditch Email Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Ditch_Email_Sent_Match_Key_s__c</fullName>
        <description>Match records where Last Ditch Email Sent is checked</description>
        <inlineHelpText>Match records where Last Ditch Email Sent is checked</inlineHelpText>
        <label>Last Ditch Email Sent Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Ditch_Email_Sent__c</fullName>
        <formula>!ISBLANK(Last_Ditch_Email_Sent_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Ditch Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Read_Date__c</fullName>
        <label>Outreach Email Read Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Read_Match_Key_s__c</fullName>
        <description>Match records where Outreach Email Read is checked</description>
        <inlineHelpText>Match records where Outreach Email Read is checked</inlineHelpText>
        <label>Outreach Email Read Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Read__c</fullName>
        <formula>!ISBLANK(Outreach_Email_Read_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outreach Email Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Replied_Date__c</fullName>
        <label>Outreach Email Replied Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Sent_Date__c</fullName>
        <label>Outreach Email Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Sent_Match_Key_s__c</fullName>
        <description>Match records where Outreach Email Sent is checked</description>
        <inlineHelpText>Match records where Outreach Email Sent is checked</inlineHelpText>
        <label>Outreach Email Sent Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outreach_Email_Sent__c</fullName>
        <formula>!ISBLANK(Outreach_Email_Sent_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outreach Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Perm_to_Conn_With_Pharma_Match_Key_s__c</fullName>
        <description>Match records where Permission to Connect With Pharma is checked</description>
        <inlineHelpText>Match records where Permission to Connect With Pharma is checked</inlineHelpText>
        <label>Perm to Conn With Pharma Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission_to_Connect_with_Pharma__c</fullName>
        <formula>!ISBLANK(Perm_to_Conn_With_Pharma_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Permission to Connect with Pharma</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pharma_PTC_Alert_Match_Key_s__c</fullName>
        <description>Match records where Pharma PTC Alert Sent is checked</description>
        <inlineHelpText>Match records where Pharma PTC Alert Sent is checked</inlineHelpText>
        <label>Pharma PTC Alert Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reached_Provider_Match_Key_s__c</fullName>
        <description>Match records where Reached Provider is checked</description>
        <inlineHelpText>Match records where Reached Provider is checked</inlineHelpText>
        <label>Reached Provider Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Replied_to_Last_Ditch_Email_Match_Key_s__c</fullName>
        <description>Match records where Replied to Last Ditch Email is checked</description>
        <inlineHelpText>Match records where Replied to Last Ditch Email is checked</inlineHelpText>
        <label>Replied to Last Ditch Email Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Replied_to_Last_Ditch_Email__c</fullName>
        <formula>!ISBLANK(Replied_to_Last_Ditch_Email_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Replied to Last Ditch Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replied_to_Outreach_Email_Match_Key_s__c</fullName>
        <description>Match records where Replied to Outreach Email is checked</description>
        <inlineHelpText>Match records where Replied to Outreach Email is checked</inlineHelpText>
        <label>Replied to Outreach Email Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Replied_to_Outreach_Email__c</fullName>
        <formula>!ISBLANK(Replied_to_Outreach_Email_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Replied to Outreach Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Screened_Match_Key_s__c</fullName>
        <description>Match records where Screened is checked</description>
        <inlineHelpText>Match records where Screened is checked</inlineHelpText>
        <label>Screened  Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Screened__c</fullName>
        <formula>!ISBLANK(Screened_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Screened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer_Date__c</fullName>
        <description>Earliest Show to Customer Date</description>
        <inlineHelpText>Earliest Show to Customer Date</inlineHelpText>
        <label>Show to Customer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer_Match_Key_s__c</fullName>
        <description>Match records where show to customer is checked</description>
        <inlineHelpText>Match records where show to customer is checked</inlineHelpText>
        <label>Show to Customer Match Key(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_to_Customer__c</fullName>
        <formula>!ISBLANK(Show_to_Customer_Match_Key_s__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show to Customer</label>
        <type>Checkbox</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>PID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PatientService.cls
public with sharing class PatientService {


    //Update Match Admin Panel
    public static void updateMatchPanelFields(Set<Id> patientIds) {
        //Query all Match Records for all Accounts
        List<Patient__c> patients = PatientSelector.matchRecordsByPatient(patientIds);
        //For each account, cycle through the match records
        for (Patient__c patient : patients) {
            //if (patient.Match_Records__r.size() == 0)continue;
            String showToCustomerKeys = '';
            String outreachEmailSentKeys = '';
            String outreachEmailReadKeys = '';
            String repliedToOutreachKeys = '';
            String ctaContactKeys = '';
            String lastDitchEmailKeys = '';
            String lastDitchRepliedKeys = '';
            String reachedProviderKeys = '';
            String informedKeys = '';
            String permConnectKeys = '';
            String pharmaPTCKeys = '';
            String screenedKeys = '';
            String enrolledKeys = '';
            String closedKeys = '';
            Date showToCustomerDate;
            Date outreachEmailSent;
            Date outreachEmailRead;
            Date repliedToOutreachEmail;
            Date ctaContactAttempted;
            Date lastDitchEmailSent;
            Date lastDitchEmailReplied;
            Date reachedProvider;
            Date informed;
            Date pharmaPermissionToConnect;
            Date ptcAlertSent;
            Date screenedDate;
            Date enrolledDate;
            Date closedDate;

            for (Match_Record__c matchRecord : patient.Match_Records__r) {
                showToCustomerKeys = buildMatchKeyString('Show_to_Customer__c', showToCustomerKeys, matchRecord);
                outreachEmailSentKeys = buildMatchKeyString('Outreach_Email_Sent__c', outreachEmailSentKeys, matchRecord);
                outreachEmailReadKeys = buildMatchKeyString('Outreach_Email_Read__c', outreachEmailReadKeys, matchRecord);
                repliedToOutreachKeys = buildMatchKeyString('Replied_to_Outreach_Email__c', repliedToOutreachKeys, matchRecord);
                ctaContactKeys = buildMatchKeyString('Contact_Attempted__c', ctaContactKeys, matchRecord);
                lastDitchEmailKeys = buildMatchKeyString('Last_Ditch_Email_Sent__c', lastDitchEmailKeys, matchRecord);
                lastDitchRepliedKeys = buildMatchKeyString('Replied_to_Last_Ditch_Email__c', lastDitchRepliedKeys, matchRecord);
                reachedProviderKeys = buildMatchKeyString('Contact_Achieved__c', reachedProviderKeys, matchRecord);
                informedKeys = buildMatchKeyString('Referred__c', informedKeys, matchRecord);
                permConnectKeys = buildMatchKeyString('Permission_to_Connect_with_Pharma__c', permConnectKeys, matchRecord);
                pharmaPTCKeys = buildMatchKeyString('Pharma_PTC_Alert_Sent__c', pharmaPTCKeys, matchRecord);
                screenedKeys = buildMatchKeyString('Screened__c', screenedKeys, matchRecord);
                enrolledKeys = buildMatchKeyString('Enrolled__c', enrolledKeys, matchRecord);
                closedKeys = buildMatchKeyString('Closed__c', closedKeys, matchRecord);
                showToCustomerDate = getFirstDate('Date_Show_to_Pharma__c', showToCustomerDate, matchRecord);
                outreachEmailSent = getFirstDate('Date_Outreach_Email_Sent__c', outreachEmailSent, matchRecord);
                outreachEmailRead = getFirstDate('Date_Outreach_Email_Read__c', outreachEmailRead, matchRecord);
                repliedToOutreachEmail = getFirstDate('Date_Replied_to_Outreach_Email__c', repliedToOutreachEmail, matchRecord);
                ctaContactAttempted = getFirstDate('Date_Contact_Attempted__c', ctaContactAttempted, matchRecord);
                lastDitchEmailSent = getFirstDate('Date_Last_Ditch_Email_Sent__c', lastDitchEmailSent, matchRecord);
                lastDitchEmailReplied = getFirstDate('Date_Replied_to_Last_Ditch_Email__c', lastDitchEmailReplied, matchRecord);
                reachedProvider = getFirstDate('Date_Contact_Achieved__c', reachedProvider, matchRecord);
                informed = getFirstDate('Date_Referred__c', informed, matchRecord);
                pharmaPermissionToConnect = getFirstDate('Date_Pharma_Permission_to_Connect__c', pharmaPermissionToConnect, matchRecord);
                ptcAlertSent = getFirstDate('Date_PTC_Alert_Sent__c', ptcAlertSent, matchRecord);
                screenedDate = getFirstDate('Date_Screened__c', screenedDate, matchRecord);
                enrolledDate = getFirstDate('Date_Enrolled__c', enrolledDate, matchRecord);
                closedDate = getFirstDate('Date_Closed__c', closedDate, matchRecord);
            }
            patient.Show_to_Customer_Match_Key_s__c = showToCustomerKeys.removeEnd(',');
            patient.Outreach_Email_Sent_Match_Key_s__c = outreachEmailSentKeys.removeEnd(',');
            patient.Outreach_Email_Read_Match_Key_s__c = outreachEmailReadKeys.removeEnd(',');
            patient.Replied_to_Outreach_Email_Match_Key_s__c = repliedToOutreachKeys.removeEnd(',');
            patient.CTA_Contact_Attempted_Match_Key_s__c = ctaContactKeys.removeEnd(',');
            patient.Last_Ditch_Email_Sent_Match_Key_s__c = lastDitchEmailKeys.removeEnd(',');
            patient.Replied_to_Last_Ditch_Email_Match_Key_s__c = lastDitchRepliedKeys.removeEnd(',');
            patient.Reached_Provider_Match_Key_s__c = reachedProviderKeys.removeEnd(',');
            patient.Informed_Match_Key_s__c = informedKeys.removeEnd(',');
            patient.Perm_to_Conn_With_Pharma_Match_Key_s__c = permConnectKeys.removeEnd(',');
            patient.Pharma_PTC_Alert_Match_Key_s__c = pharmaPTCKeys.removeEnd(',');
            patient.Screened_Match_Key_s__c = screenedKeys.removeEnd(',');
            patient.Enrolled_Match_Key_s__c = enrolledKeys.removeEnd(',');
            patient.Closed_Match_Key_s__c = closedKeys.removeEnd(',');
            patient.Show_to_Customer_Date__c = showToCustomerDate;
            patient.Outreach_Email_Sent_Date__c = outreachEmailSent;
            patient.Outreach_Email_Read_Date__c = outreachEmailRead;
            patient.Outreach_Email_Replied_Date__c = repliedToOutreachEmail;
            patient.CTA_Contacted_Attempted_Date__c = ctaContactAttempted;
            patient.Last_Ditch_Email_Sent_Date__c = lastDitchEmailSent;
            patient.Last_Ditch_Email_Replied_Date__c = lastDitchEmailReplied;
            patient.Reached_Provider_Date__c = reachedProvider;
            patient.Informed_Date__c = informed;
            patient.Permission_to_Connect_with_Pharma_Date__c = pharmaPermissionToConnect;
            patient.Pharma_PTC_Alert_Date__c = ptcAlertSent;
            patient.Screened_Date__c = screenedDate;
            patient.Enrolled_Date__c = enrolledDate;
            patient.Closed_Date__c = closedDate;

        }

        update patients;
    }

    private static String buildMatchKeyString(String fieldName, String matchKeyString, Match_Record__c matchRecord) {
        Boolean fieldChecked = (Boolean) matchRecord.get(fieldName);
        if (fieldChecked) {
            matchKeyString += (String) matchRecord.get('Match_Key__c') + ',';
        }
        return matchKeyString;
    }

    private static Date getFirstDate(String fieldName, Date currentDate, Match_Record__c matchRecord) {
        Map<String, Schema.DescribeFieldResult> finalMap =
                Utils.getFieldMetaData(Match_Record__c.getSObjectType().getDescribe(), new Set<String>{
                        fieldName
                });
        Date matchRecordDate;
        if (finalMap.get(fieldName).getType() == Schema.DisplayType.DATE) {
            matchRecordDate = (Date) matchRecord.get(fieldName);
        } else if (finalMap.get(fieldName).getType() == Schema.DisplayType.DATETIME) {
            matchRecordDate = Date.valueOf(getLocalDateTime((Datetime) matchRecord.get(fieldName)));
        }
        if (matchRecordDate != null) {
            if (currentDate == null || matchRecordDate < currentDate) {
                return matchRecordDate;
            }
        }
        return currentDate;
    }

    public static Datetime getLocalDateTime(Datetime g) {
        if (g == null){
            return null;
        }
        Datetime l = g.date();
        l = l.addHours(g.hour());
        l = l.addMinutes(g.minute());
        l = l.addSeconds(g.second());
        return l;
    }

}