objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Match_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RestTests.cls
@istest
public class RestTests {
    static testMethod void callMethods(){
        List <Match_Record__c> mrList = new List <Match_Record__c>();
        Match_Record__c mr = new Match_Record__c();
        mr.Name = '1234';
        mr.Match_ID__c = '1234';
        mrList.add(mr);
        insert mrList;
        
        Test.startTest();

            RestResponse res = new RestResponse();
            RestRequest req = new RestRequest(); 			
			
            req.httpMethod = 'GET';
            req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated 
            req.requestURI = '/services/apexrest/mrCreate/doPost' ;  
            RestContext.request = req;
            RestContext.response = res;

			
		Test.stopTest();   
        
    	mrCreate.restMethod();
    	mrUpdate.restMethod();
    	mrResponse.restMethod();
    }
}