objects/Match_Record__c.object
<CustomObject>
    <fields>
        <fullName>Match_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Internal Only</inlineHelpText>
        <label>Match ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Match Record</label>
    <nameField>
        <label>Match Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/mrResponse.cls
@RestResource(urlMapping='/mrResponse')
global class mrResponse {
    @HTTPGet
    //This will query newly portal created Match Records
    global static List<Match_Record__c> getNewMRs() {
    	List <Match_Record__c> insertedMRs = [SELECT Name, Match_ID__c, Id 
                                                FROM Match_Record__c
                                               WHERE CreatedDate > :Datetime.now().addMinutes(-2)];
    	return insertedMRs;
    }
    //This will query newly portal updated Match Records
    global static List<Match_Record__c> getUpdatedMR(){
    	List <Match_Record__c> updatedMR = [SELECT Name, Match_ID__c, Id
                                              FROM Match_Record__c
                                             WHERE SystemModStamp = :Datetime.now()
                                             LIMIT 1];
        return updatedMR;
    }
    public static void restMethod(){
    	Integer i = 0;
    	i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;

  }
}