objects/NPI_Records__c.object
<CustomObject>
    <fields>
        <fullName>Total_Samples__c</fullName>
        <description>Updated via Apex Class NpiService</description>
        <label>Total Samples</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NPI Record</label>
    <nameField>
        <label>NPI Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPI Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NpiService.cls
public with sharing class NpiService {

    public static void updateTotalSamples(Set<Id> npiIds){
        Map<Id,Integer> samplesByNpi = SampleSelector.querySampleCountByNpi(npiIds);
        List<NPI_Records__c> npiRecordsToUpdate = new List<NPI_Records__c>();
        for (Id npiId : samplesByNpi.keySet()) {
            npiRecordsToUpdate.add(new NPI_Records__c(Id = npiId, Total_Samples__c = samplesByNpi.get(npiId)));
        }
        if(npiRecordsToUpdate !=  null){
            System.debug('===npiservice update: '+npiRecordsToUpdate);
            update npiRecordsToUpdate;
        }
    }
}