objects/Scheduled_Record_Update__c.object
<CustomObject>
    <description>Custome Object to manage process builder schedules</description>
    <fields>
        <fullName>CRON_Expression__c</fullName>
        <inlineHelpText>Generate CRON here: https://www.freeformatter.com/cron-expression-generator-quartz.html</inlineHelpText>
        <label>CRON Expression</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <inlineHelpText>Leave this blank, it will auto-populate when the job is scheduled.</inlineHelpText>
        <label>JobId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Scheduled Record Update</label>
    <nameField>
        <label>Scheduled Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Record Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RecordUpdateServiceTest.cls
@IsTest
private class RecordUpdateServiceTest {
    private static final String CRON_EXP = '0 0 0 1 1 ? 2025';

    @IsTest
    private static void test_ScheduleUpdate() {

        Scheduled_Record_Update__c[] schedRecords = (Scheduled_Record_Update__c[])TestFactory.createSObjectList(
                new Scheduled_Record_Update__c(
                        Name = 'Test Record',
                        CRON_Expression__c = CRON_EXP
                ),1);
        RecordUpdateService.scheduleUpdate(schedRecords);

    }
    @IsTest
    private static void test_DeleteSchedule(){
        Test.startTest();
        test_ScheduleUpdate();

        CronTrigger ct = [
                SELECT Id
                FROM CronTrigger
                WHERE CronExpression = :CRON_EXP
                LIMIT 1
        ];

        Scheduled_Record_Update__c[] schedRecords = (Scheduled_Record_Update__c[])TestFactory.createSObjectList(
                new Scheduled_Record_Update__c(
                        Name = 'Test Record',
                        CRON_Expression__c = CRON_EXP,
                        JobId__c = ct.Id
                ),1);

        RecordUpdateService.deleteSchedule(schedRecords);
        Test.stopTest();

    }

}