objects/Scheduled_Record_Update__c.object
<CustomObject>
    <description>Custome Object to manage process builder schedules</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>200</defaultValue>
        <inlineHelpText>Default is 200. Lower this if you run into CPU Timeout issues or Record-locking issues.</inlineHelpText>
        <label>Batch Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <inlineHelpText>Leave this blank, it will auto-populate when the job is scheduled.</inlineHelpText>
        <label>JobId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOQL_Query__c</fullName>
        <inlineHelpText>Must include the name of the field to be modified (the &quot;Write To Field&quot;)</inlineHelpText>
        <label>SOQL Query</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Write_Text__c</fullName>
        <inlineHelpText>Write text that will trigger a process in Process Builder</inlineHelpText>
        <label>Write Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Write_To_Field__c</fullName>
        <label>Write To Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Scheduled Record Update</label>
    <nameField>
        <label>Scheduled Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Record Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RecordUpdateScheduler.cls
global class RecordUpdateScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {
        String jobId = sc.getTriggerId();
        jobId = jobId.substring(0, jobId.length() - 3);
        system.debug('===JobId: ' + jobId);
        List<Scheduled_Record_Update__c> scheduledProcesses = [
                SELECT
                        SOQL_Query__c,
                        Write_Text__c,
                        Write_To_Field__c,
                        Batch_Size__c
                FROM Scheduled_Record_Update__c
                WHERE JobId__c = :jobId
                LIMIT 1
        ];
        Scheduled_Record_Update__c scheduledProcess = (scheduledProcesses.size() == 1) ? scheduledProcesses.get(0) : null;
        if (scheduledProcess == null) {
            return ;
        }
        Integer batchSize = scheduledProcess.Batch_Size__c != null ? Integer.valueOf(scheduledProcess.Batch_Size__c) : 200;
        Database.executeBatch(new RecordUpdateBatch(
                scheduledProcess.SOQL_Query__c,
                scheduledProcess.Write_To_Field__c,
                scheduledProcess.Write_Text__c), batchSize);
    }
}