objects/Scheduled_Record_Update__c.object
<CustomObject>
    <description>Custome Object to manage process builder schedules</description>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <defaultValue>200</defaultValue>
        <inlineHelpText>Default is 200. Lower this if you run into CPU Timeout issues or Record-locking issues.</inlineHelpText>
        <label>Batch Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CRON_Expression__c</fullName>
        <inlineHelpText>Generate CRON here: https://www.freeformatter.com/cron-expression-generator-quartz.html</inlineHelpText>
        <label>CRON Expression</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOQL_Query__c</fullName>
        <inlineHelpText>Must include the name of the field to be modified (the &quot;Write To Field&quot;)</inlineHelpText>
        <label>SOQL Query</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Write_Text__c</fullName>
        <inlineHelpText>Write text that will trigger a process in Process Builder</inlineHelpText>
        <label>Write Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Write_To_Field__c</fullName>
        <label>Write To Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Scheduled Record Update</label>
    <nameField>
        <label>Scheduled Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Record Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduledRecordUpdateTriggerHandlerTest.cls
@IsTest
private class ScheduledRecordUpdateTriggerHandlerTest {
    private static final String CRON_EXP = '0 0 0 1 1 ? 2025';

    @TestSetup
    public static void SetupObjects() {
        Scheduled_Record_Update__c[] records = (Scheduled_Record_Update__c[])TestFactory.createSObjectList(
                new Scheduled_Record_Update__c(
                        Name = 'Test Record',
                        CRON_Expression__c = CRON_EXP,
                        Batch_Size__c = 100,
                        SOQL_Query__c = 'SELECT Id, Name FROM Account LIMIT 1',
                        Write_To_Field__c = 'Name',
                        Write_Text__c = 'Test'
                ),1, true);
    }

    @IsTest
    public static void testUpdateTrigger() {
        Scheduled_Record_Update__c record = [SELECT Id, Write_Text__c FROM Scheduled_Record_Update__c LIMIT 1];
        record.Write_Text__c = 'Test Update';
        update record;
    }

    @IsTest
    public static void testDeleteTrigger() {
        Scheduled_Record_Update__c record = [SELECT Id, Write_Text__c FROM Scheduled_Record_Update__c LIMIT 1];
        delete record;
    }


}