objects/Scheduled_Record_Update__c.object
<CustomObject>
    <description>Custome Object to manage process builder schedules</description>
    <fields>
        <fullName>CRON_Expression__c</fullName>
        <inlineHelpText>Generate CRON here: https://www.freeformatter.com/cron-expression-generator-quartz.html</inlineHelpText>
        <label>CRON Expression</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <inlineHelpText>Leave this blank, it will auto-populate when the job is scheduled.</inlineHelpText>
        <label>JobId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Scheduled Record Update</label>
    <nameField>
        <label>Scheduled Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Record Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RecordUpdateService.cls
public with sharing class RecordUpdateService {

    public static void scheduleUpdate(List<Scheduled_Record_Update__c> newRecords) {
        for (Scheduled_Record_Update__c scheduledRecordUpdate : newRecords) {
            String jobId = System.schedule(scheduledRecordUpdate.Name,
                    scheduledRecordUpdate.CRON_Expression__c,
                    new RecordUpdateScheduler());
            scheduledRecordUpdate.JobId__c = jobId;
        }
    }
    public static void deleteSchedule(List<Scheduled_Record_Update__c> records) {
        for (Scheduled_Record_Update__c scheduledRecordUpdate : records) {
            try {
                System.debug('===JobId to Abort: '+ scheduledRecordUpdate.JobId__c);
                System.abortJob(scheduledRecordUpdate.JobId__c);
            } catch (Exception e) {
                system.debug('Error Deleting Job: '+ e);
            }
            if (!Trigger.isExecuting || !Trigger.isDelete) {
                scheduledRecordUpdate.JobId__c = null;
            }

        }
    }
}